### ISSUE TITLE
Fix decimals and other offset settings

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/com.ruuvi.station.webui#1]
Check that values are shown with correct precisions and use same number of decimals with the mobile apps if not already doing so.

One issue I noticed is that if I set 1,00C temperature offset on the mobile but on the web it is like this:

![image](https://user-images.githubusercontent.com/1311912/128296959-cb3bd2cb-9334-46b6-bde7-c366f7694171.png)

**Comment by markoaamunkajo** [comment]
QA passed
Opened other issue for possible humidity calibration bug
