### ISSUE TITLE
Changes to blue boxes on top of sensor view

### ISSUE THREAD

**Issue by sini-maaria** [ruuvi/com.ruuvi.station.webui#100]
1. Add info icon for all the blue boxes:
- Info icon opens a popup. 
- @laurijamsa will provide the text content for popups.
- Position 8-10px from the right corner. 
- Icon size 16px. 
- Icon svg file in Telegram.

2. Add subtitles for boxes
- "Main Sensors" and "Others"
- Add Hide link next to "Others"
- Remember later if user has hidden the boxes.

3. Change sensor name font under the measurement (on blue boxes) to Mulish SemiBold Italic
4. Move °C, % and other marks higher.
5. Add min-width for boxes to 200px.

6. Move all the "Others" (in the picture) here from "More info" on the bottom
- Remove the same content from "More info" section

7. Change Graph title 
- to "History" and
- add "Selected:" text before selected sensor name

![Screenshot 2021-12-20 at 12 05 57](https://user-images.githubusercontent.com/19531763/146749933-47016edd-6e70-4229-9839-c04129ccced7.png)

**Comment by laurijamsa** [comment]
The info popups could be toast messages instead of popups. It would also simplify user experience because then manual popup closing would not be needed. Let's try with toasts and we'll see how it goes.

**Comment by laurijamsa** [comment]
Max width of the boxes should be defined like on the design:

![image](https://user-images.githubusercontent.com/1311912/155473309-d3f25191-3b1c-42a9-8dfa-17a49c6e2ea1.png)

Main Sensors and Other Sensors translations are missing, and the "Other Sensors" could be "Additional Data" (Finnish: Pääanturit and Lisätiedot):

![image](https://user-images.githubusercontent.com/1311912/155473487-871e254c-0802-4b65-a718-591888dd6efe.png)

This hoovering helper looks good to me but the same should happen also on the "Zoom (i)" then:

![image](https://user-images.githubusercontent.com/1311912/155473867-f3e16928-356e-4ef2-a91c-fc68862c2f77.png)
![image](https://user-images.githubusercontent.com/1311912/155473902-1612330b-d94c-40b3-9921-06b6e07ddbda.png)

**Comment by laurijamsa** [comment]
This issue will get some new instructions in near future so let's pause working with it until then.

**Comment by io53** [comment]
Todo:
Make 2 sensor reading boxes per row fit on mobile

**Comment by sini-maaria** [comment]
Also noticed this:
- Reduce the line height on "movement counter"

![Screenshot 2022-03-15 at 8 20 03](https://user-images.githubusercontent.com/19531763/158321896-ef8430d9-577e-42ef-882e-95b401700368.png)

**Comment by laurijamsa** [comment]
Here are finally preliminary strings for the units:


```
Temperature

   Tip: You can change the unit in settings. Available units are: Celsius (°C), Fahrenheit (°F) and Kelvin (K).



Humidity

   Tip: You can change the unit in settings. Available units are: Relative (%), absolute (g/m^3) and dew point (°).



Pressure

   Tip: You can change the unit in settings. Available units are: Pascal (Pa), hectopascal (hPa), millimetre of mercury (mmHg) and inch of mercury (inHg).



Movement Counter

   Every time Ruuvi sensor is moved, its internal movement counter is increased.

   Tip: Maximum value of the counter is 255 and when reached, it starts again from zero. When the sensor is rebooted, the counter is also automatically reset to zero.



Battery Voltage

   We recommend replacing the battery when voltage is lower than 2,4 volts in room temperature.

   Tip: When the temperature of the battery goes down, voltage readings also decrease. But this necessarily doesn't mean that the battery would be empty.



Acceleration X Y Z

   Ruuvi sensor's three-dimensional digital accelerometer continuously measures proper acceleration in g (g ≈ 9,81 m/s^2). 

   Tip: Acceleration values can tell you orientation of a stationary sensor.



Signal Strength (RSSI)

   Received signal strength is measured by receiver device in decibel milliwatts (dBm). Bigger the number, stronger the received signal.

   Tip: Every 3 dB step doubles the received radio energy. Meaning, for example, -37 dBm is two times stronger than -40 dBm.



Measurement Sequence Number

   When Ruuvi sensor is refreshing its measurements (every ~2,5 seconds), the measurement sequence number is increased. Maximum value of the counter is 16 bits (65536) and when reached, it starts again from zero.

   Tip: When the sensor is rebooting, the counter is automatically reset to zero. By examinating history cycles of the measurement counter, you can see if the sensor has rebooted unintentionally.

```

**Comment by dgcccu** [comment]
Better wording:
You can change the unit**s** in

 (°F) and Kelvin (K)
 (°F) and Kelvin (**°**K)

volts **at** room temperature.

voltage _readings_ also decreases. (( omit readings))

battery is nearly depleted.         or nearly exhausted.

measures _proper_ acceleration.        (((( omit proper))))

 three-dimensional digital 
3-axis (((omit digital)))

measured by **receiving**  device 

**larger** the number

counter is 65,53**5** and when reached.  ((((omit bits,  max value is actually 65,535)))

When the sensor is rebooting, the counter is automatically reset to zero
When the sensor resets the counter is set to zero.

rebooted unintentionally.
reset unexpectedly

**Comment by markoaamunkajo** [comment]
Will leave this card for Lauri so many things were listed.
