### ISSUE TITLE
Heavy traffic when selecting long history on dashboard

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/com.ruuvi.station.webui#105]
Can we optimise somehow?

![image](https://user-images.githubusercontent.com/1311912/147912410-57b979ea-8d3b-43aa-8b83-ae110a7b0275.png)

**Comment by ojousima** [comment]
I think the data fetch should be paginated by application, e.g. one month at a time. Current max limit on server side is 144000 results / sensor, so 25 * 144000 datapoints for a pro user. 

The data itself is already tightly packed BLE-data, although coded in hex.

**Comment by ojousima** [comment]
Related, AWS Dynamo can return up to 1 MB of data per query. Single datapoint is about 210 bytes, so a single query can return ~4800 datapoints tops even if "limit" parameter is higher. 

It also should be noted that 1 MB of Dynamo data is more when sent over as JSON. 

History fetching should be paginated, e.g. limit = 1000 and fetch next 1000 datapoints with until = lastDataPoint.timestamp

**Comment by io53** [comment]
Pagination would make the loading more interactive if we show the data as it comes in, but it would result in a lot more requests and would be using the same amount of bandwidth in the end.

Currently there is no way to select less datapoints if you want data from say 6 months back, even tho only one datapoint per day would be enough for the dashboard view.
Maybe an even more sparse data fetching method could be implemented in the backend?

**Comment by ojousima** [comment]
> Maybe an even more sparse data fetching method could be implemented in the backend?

It would be possible to decimate the data, eg. `&decimate=3` results in only 1/3 datapoints being returned

**Comment by io53** [comment]
This also solves #106
