### ISSUE TITLE
Show partial data while fetching history?

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/com.ruuvi.station.webui#106]
If I have a relatively slow internet connection and timespan is long on dashboard/sensor view, it takes up to several minutes to show anything and it is not a good user experience. Could we show the most recent data right away once loaded and then append the graphs at the same time when rest of the history is being loaded?

Loading state:

![image](https://user-images.githubusercontent.com/1311912/148562829-8581e7e9-26b3-430c-8c93-75ef22762c68.png)

![image](https://user-images.githubusercontent.com/1311912/148562909-dc9c6aa3-2440-4e4b-bb16-fc3406db18f5.png)

**Comment by ojousima** [comment]
This is related to #105, pagination
