### ISSUE TITLE
temperature alerts in F vary slightly from requested

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.webui#108]
Set temperature alert for Ruuvi Ad03 fridge vi input box at 35F and 40F

Immediately displays alert at 35.01 and 39.99

Suggest alerts near integer values be displayed as integer for F and  (even ?) tenths for C

**Comment by laurijamsa** [comment]
Ruuvi Cloud is sending the email alerts, this is not related to the web user interface. We've occasionally received feedback from users who would like to be able to configure their sensors to show less resolution (1.11C -> 1.1 Cor even 1C). If we'd like to implement this, we could add a user setting in the cloud that would show desired resolution to user in mobile and web, and additionally send alerts only when there is a big enough change (not 0.01C but 0.1C for example). I will open an issue to the cloud repo about this idea and will refer back to this (closed) issue.
