### ISSUE TITLE
Enhance history caching on the browser

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/com.ruuvi.station.webui#111]
If I open a sensor and select history time 1 month, and then change history length to 1 week, full 1 week history is downloaded again from the server even it was already downloaded once when 1 month was selected. To me it seems that this caching is working better on the dashboard.

**Comment by io53** [comment]
Dashboard view is as before. But the sensor page now downloads data in batches of 1000 readings, verifying if values are cached is a bit more tricky now. But at least going from bigger -> shorter history should be easy to fix

**Comment by io53** [comment]
selecting 2d history length has a data gap

**Comment by laurijamsa** [comment]
I haven't faced bugs and downloading is faster now, so, ready to be deployed!

**Comment by markoaamunkajo** [comment]
QA passed
