### ISSUE TITLE
Gap in the data if viewing "Last 2 Days" or more in the big view

### ISSUE THREAD

**Issue by Scrin** [ruuvi/com.ruuvi.station.webui#112]
I recently noticed that there seems to be a gap appearing in the data if I view "Last 2 days" in the big graph view. This is most visible with my freezer tag:
![image](https://user-images.githubusercontent.com/6617316/149567329-75efb8e8-0003-42ba-88c5-e30e31ef02e0.png)
With "Last 1 Day" the data is there, so it's probably not an issue with the gateway itself:
![image](https://user-images.githubusercontent.com/6617316/149567470-48786cb6-c4b0-4fbc-a0af-c5412a9723ef.png)
Interestingly enough the small view does not have this issue, here is "Last 2 days" in the small view:
![image](https://user-images.githubusercontent.com/6617316/149567558-36d69511-53d4-4beb-8fe9-eacb06ffec94.png)

This seems to affect all measurements of all of my tags, perhaps related to the recently added pagination?

**Comment by io53** [comment]
Yes, it is indeed related to the pagination. It is fixed and be will be deployed soon 👍

**Comment by io53** [comment]
The gap should be gone now

**Comment by Scrin** [comment]
Confirmed, I can't spot any more unexpected gaps in any time range
