### ISSUE TITLE
Alert custom description should have character limit

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.webui#113]
Description:

Alerts custom description field has unlimited characters.

Let's add limit to protect against any possible layout breaking issues on emails and  all clients.
![Screenshot 2022-01-16 at 18 17 00](https://user-images.githubusercontent.com/50437378/149657709-9774221a-f52a-4cff-8653-3f3ee2e7bea7.png)
![Screenshot 2022-01-16 at 18 20 12](https://user-images.githubusercontent.com/50437378/149657765-0eb41ec5-59fe-443d-9bf8-72a955e1e73d.png)

**Comment by laurijamsa** [comment]
Seems that character limit is 64. On Android it's 100. When using Android, to me, it feels like 100 is not too much. So, let's use 100 here too.
