### ISSUE TITLE
Use superscript in UI when in use

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.webui#117]
Description:

User chooses to show absolute humidity units in Ruuvi Station web. In UI these units are shown with g/m^3

Expected: correct way to display m^3 would be superscript as in apps, as long as font supports this.
Low priority.

**Comment by laurijamsa** [comment]
Not working in production:

![image](https://user-images.githubusercontent.com/1311912/156541793-6aa08ad6-8738-49b1-875f-3c3e833e1dc5.png)
