### ISSUE TITLE
The sensor need ... should be needs - nit

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.webui#119]
No data.
The sensor need to be in range of a gateway
would be
the sensor need**s** to

**Comment by laurijamsa** [comment]
Opened a new one in the correct repo: https://github.com/ruuvi/station.localization/issues/85

**Comment by ojousima** [comment]
I did not find the string in localization repo master, so it seems to be Web UI issue

**Comment by io53** [comment]
@ojousima it's in the dev branch

**Comment by DG12** [comment]
I had no idea this would be anything other than an insignificant effort, sorry.
