### ISSUE TITLE
Detail page Loops for a 60 seconds if no data is found - v0.28 - nuisance 

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.webui#120]
RuuviSensor F7:B7:74:47:22:AB shows "Nodata" on main page. 

Either clicking on it or
clicking on adjacent sensor then clicking > displays  sliding "loading" bar for 60 seconds.  
no message is displayed.

**Comment by laurijamsa** [comment]
I believe this is already fixed. Please reopen if not.
