### ISSUE TITLE
adjusting temperature alert limits says: Missing Argument - 

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.webui#130]
After setting limits missing argument appears for 2 seconds. both versions 2.9 and 2.10
<img width="660" alt="SetTempAlert_missingArg" src="https://user-images.githubusercontent.com/2365961/150364433-e0d7f98b-923d-4027-adcc-7e1ec817b20e.png">

**Comment by laurijamsa** [comment]
I have reproduced this:

https://user-images.githubusercontent.com/1311912/150756750-3c864e5f-b9fc-4704-baa0-67d4a3e4a59c.mov

**Comment by laurijamsa** [comment]
No more Missing argument message but now I noticed that when I add a custom description and press ok and I get Successfully saved message, the description is still not shown on the site:

![image](https://user-images.githubusercontent.com/1311912/151191107-85bdb5e4-fda7-42b0-a2f8-61ecb5d16e4f.png)

But when I edit it again, it's there on the popsup:

![image](https://user-images.githubusercontent.com/1311912/151191318-474538a3-9d1f-46d9-92af-86c95a8cb55c.png)

Then I edit it again:

![image](https://user-images.githubusercontent.com/1311912/151191373-682d768f-6469-4509-9aec-21d73c8df38a.png)

And then it gets updated on the page:

![image](https://user-images.githubusercontent.com/1311912/151191414-a2a26085-d53f-471b-b72e-191bde566c91.png)
