### ISSUE TITLE
UI fix - small changes

### ISSUE THREAD

**Issue by sini-maaria** [ruuvi/com.ruuvi.station.webui#146]
![Screenshot 2022-02-24 at 10 40 43](https://user-images.githubusercontent.com/19531763/155489238-5b0914d6-18c7-4891-9893-53cd8332230b.png)

![Screenshot 2022-02-24 at 10 42 12](https://user-images.githubusercontent.com/19531763/155489277-8c2318db-1ae4-4a4f-bfd4-55479ced5ba7.png)

![Screenshot 2022-02-24 at 10 42 29](https://user-images.githubusercontent.com/19531763/155489319-5a04f8f7-594d-4dab-8704-9be2e0d35927.png)

![Screenshot 2022-02-24 at 10 43 21](https://user-images.githubusercontent.com/19531763/155489447-c682e6cf-f560-439a-be90-939eb4fb2de7.png)

**Comment by sini-maaria** [comment]
![Screenshot 2022-02-24 at 12 24 26](https://user-images.githubusercontent.com/19531763/155506229-48015f7d-5e55-4bbb-89b8-b3d4a0daf9f8.png)

**Comment by sini-maaria** [comment]
1. Remove link from Zoom, leave the info toast. Add same hover effect to info toast as elsewhere.
2. Add underline to global link styles. (Here "Export")

![Screenshot 2022-02-25 at 10 52 09](https://user-images.githubusercontent.com/19531763/155684972-a8d1deca-0bc6-494d-b7b0-225636a1828a.png)

**Comment by laurijamsa** [comment]
Footer font size is not reduced from 18px to 16px yet.

Tha border color is not changed or removed:

https://user-images.githubusercontent.com/19531763/155489319-5a04f8f7-594d-4dab-8704-9be2e0d35927.png

**Comment by sini-maaria** [comment]
Center "title section" vertically to the top area. See the image:

![Screenshot 2022-03-15 at 8 35 11](https://user-images.githubusercontent.com/19531763/158320642-05f8b137-0954-47a2-a589-ec1113009773.png)

Info icon is not visible enough. Can you make it a bit darker here?

![Screenshot 2022-03-15 at 8 29 07](https://user-images.githubusercontent.com/19531763/158319961-bbb6ed68-2aa4-43b7-9c18-dd8447fcb5e4.png)

**Comment by sini-maaria** [comment]
Also:
- Reduce the subtitle font size (update time) on mobile.
