### ISSUE TITLE
CSV export includes wrong values

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.webui#151]
Timestamp,Temperature (°F),Humidity (%),Pressure (inHg),RSSI,Acceleration X,Acceleration Y,Acceleration Z,Voltage,Movement counter,   Measurement sequence number
2021-11-01T10:51:43-0400,21.34,50.28,100182,-74,40,-24,988,2623,133,30847

SB
2021-11-01T10:51:43-0400,21.34,50.28,1001.82,-74,.04,-.024,.988,2.623,133,30847
In addition pressure is in pa user wants inHg

**Comment by laurijamsa** [comment]
This is a good catch. Seems that the CSV export has many inconsistencies with the mobile apps' exports. Elias, please test this properly and fix everything you can find. The goal is to have equal exports with the mobile apps.

I noticed at least these:

F is set, still C is exported
Abs humi is set, still relative is exported, I also see on the headline [object object] when I set humidity as absolute
inHg is set, Pa is exported
hPa is set, Pa is exported
Voltage is exporting in mV, not V
Acceleration is exported in mg, not g

**Comment by laurijamsa** [comment]
@markoaamunkajo I'm assigning this to you. Please make a comprehensive export testing between Android & iOS & Web with different user account settings (language + temp/humi/press units) on all clients. Goal is to have more or less 1:1 export files on all the clients.

**Comment by markoaamunkajo** [comment]
I selected 1 month view in and made CSV export. I see duplicate entries according to measure sequence number.
I'm assuming then that not all duplicates are filtered.

[Home outdoors _20220412-1027.csv](https://github.com/ruuvi/com.ruuvi.station.webui/files/8469241/Home.outdoors._20220412-1027.csv)

**Comment by markoaamunkajo** [comment]
Also looks like testing with RuuviTag Pro without pressure sensor the values are in CSV export shown as NaN. In mobile apps we use "-" for these, shall we unify? @laurijamsa

**Comment by laurijamsa** [comment]
Yes, let's unify the NaN thing and fix the duplicated data issue.

**Comment by markoaamunkajo** [comment]
@io53 both apps use title for battery in csv = "Voltage" let's use same on web station.

**Comment by DG12** [comment]
Problems I observed previously have been corrected 0.3.1 :-)
And so fast too!
<pre><small>Timestamp,Temperature (°F),Humidity (%),Pressure (hPa),RSSI,Acceleration X,Acceleration Y,Acceleration Z,Battery Voltage,Movement Counter,Measurement Sequence Number,Tx Power
2022-05-13T17:05:29-0400,68.4,52.25,1006.83,-82,0.004,1.008,-0.048,2.728,116,22410,4

**Comment by markoaamunkajo** [comment]
Closing this issue, bugs fixed, unification done on other card
