### ISSUE TITLE
Detail popup needs better spacing - v0.2.15 - nit

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.webui#153]
<img width="511" alt="webuipopup-spacing" src="https://user-images.githubusercontent.com/2365961/159026578-0619e0f0-55f0-42a1-b375-aa553b040d17.png">

**Comment by io53** [comment]
How did you get that popup to show? We have not added any so I suppose it's some browser feature?

**Comment by DG12** [comment]
Safari special! mouseDown drag as if you were trying to move the box.
Stumbled (as usual ) up it. :-)
