### ISSUE TITLE
login language choice is En SB English  - nit

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.webui#154]
It would be prettier of spell out the languages (IMHO)
<img width="343" alt="login_EnFiSvPrettier" src="https://user-images.githubusercontent.com/2365961/159043131-98ae4841-d6b8-4e11-ac99-d4e8f1f48254.png">

**Comment by laurijamsa** [comment]
Thanks. We'll be redesigning the whole login page in near future. Closing.
