### ISSUE TITLE
After removing a sensor, sensor dropdown menu on the header is not updated and keeps showing the already removed sensor

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/com.ruuvi.station.webui#155]
Reproduce:

1) Remove a sensor

2) Notice that dashboard is loaded automatically and the removed sensor graph is not there

3) But if checking the dropdown menu, the removed sensor is still there

4) Manual command+R refresh fixes this

**Comment by markoaamunkajo** [comment]
QA passed
