### ISSUE TITLE
Iframe (or javascript) login element

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/com.ruuvi.station.webui#156]
Make it more pretty and pay attention to the SEO.

Current situation:

<img width="468" alt="image" src="https://user-images.githubusercontent.com/1311912/160268049-cb4d53b7-3acb-4857-aeef-c4cb2f0258d9.png">

<img width="686" alt="image" src="https://user-images.githubusercontent.com/1311912/160268065-502e3e4f-6e09-493c-805a-3de5dbf98861.png">

**Comment by io53** [comment]
The description text that shows on google can be changed pretty easily it seem. We just need come up with something to put there

**Comment by laurijamsa** [comment]
We have agreed that we'll try to create an inline frame element (iframe) of the login function. This way it can be embedded on Ruuvi's website.

**Comment by laurijamsa** [comment]
The iframe creates a funny size of a box:

<img width="641" alt="image" src="https://user-images.githubusercontent.com/1311912/165685069-6d641602-e0e8-4f9c-ae23-3a576747b1fd.png">

Some formatting issue:

<img width="335" alt="image" src="https://user-images.githubusercontent.com/1311912/165684876-e5826ec4-6513-4072-9937-e89973cfeac1.png">

Forwards to url https://devstation.ruuvi.com/?lng=fi#/ but Finnish language is not selected automatically on the devstation.

Let's force to capital letters like we're doing elsewhere too:

<img width="319" alt="image" src="https://user-images.githubusercontent.com/1311912/165685208-c3f1dd27-bf2b-4457-bd1a-29567738b201.png">

**Comment by laurijamsa** [comment]
This is not properly tested but we'll open new issues when needed, if needed. Closing.
