### ISSUE TITLE
Main screen tiles have incomplete data - devastation. v0.2.15

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.webui#157]
<img width="450" alt="450A-220326 1800-2220327 1750tile" src="https://user-images.githubusercontent.com/2365961/160302897-d451d152-4d2e-4b5a-b900-8f1b0abf8268.png">
<img width="1512" alt="450A-220326 1800-220327 1750" src="https://user-images.githubusercontent.com/2365961/160302900-b5bbb00d-dfbe-4715-a80f-50cc17876638.png">

**Comment by io53** [comment]
Odd, could be a bug in the cache. Is both views set to use 1 day history length?
Could you also check in another browser to see if there was a glitch when saving cache for that sensor or if you can reproduce it?

**Comment by DG12** [comment]
Argh. I hate when this happens.
Although I was able reproduce this at the time,
I cannot reproduce this now ! 

Will re-open with more detail as you suggest if I can get it to happen again.  :-{

**Comment by DG12** [comment]
Additional information. 
I just realized that this tag is out-o-range frequently between 08:00 and 10:30 Monday-Saturday
