### ISSUE TITLE
Selection of a range of graph produces unexpected truncation - an observation

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.webui#158]
This originally struck me a as a bug but as I thought about it maybe not!

I wanted to select the first half of a 2 day graph. I started in. the middle and  slid the cursor left to the start.
Apparently as I did I also slid down a little. This caused a rectangular section of the graph to be selected and when I released,,, 
Well I got exactly what I had highlighted
<img width="708" alt="SelectHalfOfGraph_orNOT" src="https://user-images.githubusercontent.com/2365961/160489746-6f8ca3dd-00e7-41df-968d-2ef77c151d69.png">
!

**Comment by laurijamsa** [comment]
I feel like this is a good feature, actually. When zooming, user can select a desired area also vertically. Using the feature feels also pretty natural to me. Wouldn't remove this option for now. Closing.
