### ISSUE TITLE
Remove sensor details from card, charts and settings if no sensor

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.webui#159]
Description:

Some RuuviTags have less sensors, for example pressure sensor not onboard.
Let's remove missing sensor details from card including:

- Box on top of chart for reading
- Chart
- Any related setting such as alert, offset correction
- Check that CSV export shows "-" in this case for sensor

**Comment by laurijamsa** [comment]
I still can see alert slider for pressure on a sensor that has no pressure sensing feature. I didn't test yet if I can see pressure offset setting because this is a shared sensor and I'm not the owner (cannot see the offset settings at all).

**Comment by markoaamunkajo** [comment]
QA passed
