### ISSUE TITLE
Use commas and 24h time format everywhere

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/com.ruuvi.station.webui#16]
![image](https://user-images.githubusercontent.com/1311912/128976166-2edccb45-e300-42be-a579-51d12ffdc96c.png)

![image](https://user-images.githubusercontent.com/1311912/128976225-1e745334-703d-45b3-98eb-80ac94a415b2.png)

![image](https://user-images.githubusercontent.com/1311912/128976293-9c096802-01e8-4092-902c-160bd0d2d0d9.png)

I think for now it's not necessary to support different date and time formats, let's just use what we use in Finland and what majority of the Europe countries use. Howeverm, if the graph lib or other libs you're using already support showing MM/DD instead of DD/MM for US people according their computer's localisation settings, then it's not needed to remove that functionality of course.

**Comment by markoaamunkajo** [comment]
QA passed
