### ISSUE TITLE
Show most recent data before starting to download history (dashboard & sensor views)

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/com.ruuvi.station.webui#162]
Currently, user has to wait until first history chunk has been downloaded before anything is shown. Depending on connection speed, this can be fast or annoying slow.

In this video, user has to wait over 10 seconds until anything is shown:

https://user-images.githubusercontent.com/1311912/164387395-19845ece-d2ce-4e37-8769-6823d8042f9e.mov

**Comment by laurijamsa** [comment]
I see some enhancement compared to the old one but I think we have still things to do because the page has to download ~1Mb of elements before it shows the most recent data and when simulating with a "slow 3G" connection, it takes up to 20 seconds (see video):

https://user-images.githubusercontent.com/1311912/165682429-689e0e84-0193-4636-9cb4-00a9f22d4336.mov

**Comment by io53** [comment]
The application bundle is quite big 🤔. This will only be loaded the first time you visit the page so I don't think it is that bad. But I'll see what is eating all the space

**Comment by io53** [comment]
@laurijamsa check if the loading is more pleasant now. It will load the same stuff, but not all at once. I can try to see what else can be done if it still is too slow, but I don't think it makes sense as it's only the initial load that's slow.

**Comment by laurijamsa** [comment]
I have tested this and I don't see improvements really. To me it seems that the 0.3.0 release shows user information faster than the unreleased 0.3.1. Below is a comparison video.

Settings: Slow 3G, disable cache, key value pairs cleared before refresh

https://user-images.githubusercontent.com/1311912/167539974-1cb0535d-7b39-40ce-ac44-a2b0fb140fe3.mov

**Comment by laurijamsa** [comment]
Made also tests with cache enabled and then toggled between 2 sensors multiple times on the devstation and station. Takes ~5 seconds before user sees even the live data and another 5-8 seconds until cached history data is shown.

Station 0.3.0:

https://user-images.githubusercontent.com/1311912/167541196-f7d8ecc4-6bd5-4098-9f2c-afcf73a8fd51.mov

Devstation 0.3.1:


https://user-images.githubusercontent.com/1311912/167541328-1b387f5d-c71d-4b6a-9448-58669046cd7b.mov

**Comment by io53** [comment]
@laurijamsa have a look now how it feels. It's at that point that if we want it faster we need to show cached values before we have fetched new once. While possible I don't think it's worth showing potentially old data.

**Comment by ojousima** [comment]
Using the new API endpoint could help here: https://docs.ruuvi.com/communication/cloud/user-api#get-your-sensors

It was added to production this week, returns latest datapoint of each sensor user has access to in one query. It also is a good endpoint for refreshing the data, replacing per-sensor query with one call to update all.

**Comment by laurijamsa** [comment]
I'm not perfectly sure if I see enhancements when toggling between sensors on "slow 3G mode" butI think we can go with these updates to the production and let's get back into this later if needed. Ready to deploy.
