### ISSUE TITLE
Implement a low battery indicator

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/com.ruuvi.station.webui#164]
Same was as on mobile:

https://github.com/ruuvi/com.ruuvi.station/issues/335

https://github.com/ruuvi/com.ruuvi.station.ios/issues/886

**Comment by laurijamsa** [comment]
I cannot remember what we agreed in the last meeting - do you need more ui guidelines before this task can be finished?

**Comment by io53** [comment]
I don't think we reached any final decision. I added "battery ok/replace no" text before the voltage in the box. In the meeting we discussed about potentially adding a warning triangle icon top right next to the info icon if the battery was low instead. What solution do we go with?

**Comment by laurijamsa** [comment]
What about this?

<img width="235" alt="image" src="https://user-images.githubusercontent.com/1311912/166659380-56f3a176-6755-41d0-8e49-811e0280b4e6.png">

<img width="228" alt="image" src="https://user-images.githubusercontent.com/1311912/166659720-41d2649b-f20e-4ff5-951f-d20bcf7c6152.png">

**Comment by io53** [comment]
I pushed a version with the same strings and android uses, below the "Battery Voltage". Have a look and see if it makes sense :)
