### ISSUE TITLE
Export does not include Tx power,  missing first line i.e. sensor name 

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.webui#165]
I really don't think it should. 
Maybe it should be removed from other formats ?
RSSI should be included as it is in the database.

IOS format includes important first line containing sensor name for example :**Ruuvi BB12 water inlet**

IOS and Android format column title are "Voltage" and "Voltage(V)". webui should remove word "Battery"

Webui:
Timestamp,Temperature (°F),Humidity (%),Pressure (inHg),RSSI,Acceleration X,Acceleration Y,Acceleration Z,Battery Voltage,Movement Counter,Measurement Sequence Number
2022-04-25T15:21:12-0400,62.96,45.12,29.77,-80,0,1.016,-0.048,2.7,113,4646

IOS:
Ruuvi BB12 water inlet
"Date","ISO8601","Temperature (°F)","Humidity (%)","Pressure (inHg)",RSSI,Acceleration X,Acceleration Y,Acceleration Z,"Voltage (V)","Movement Counter","Measurement Sequence Number","TX Power"
"2022-04-15 18:40:40",2022-04-15T22:40:40.000Z,65.38,49.06,29.52,-76,0.004,1.012,-0.040,2.696,109,787,4

Android:
Timestamp,Temperature (°F), Humidity (%), Pressure (inHg),RSSI,Acceleration X,Acceleration Y,Acceleration Z,Voltage,Movement counter,Measurement sequence number,TX Power
2022-04-15T18:55:41-0400,65.4,48.97,29.52,-75,0.004,1.008,-0.036,2.707,109,1137,4.0

**Comment by io53** [comment]
I added tx power in this issue. I don't think sensor name should be in the top row, that is usually the header row and the sensor name is in the filename. @markoaamunkajo will hunt differences in the csv format and we'll see what has to be done.
