### ISSUE TITLE
Add padding to measurement box

### ISSUE THREAD

**Issue by sini-maaria** [ruuvi/com.ruuvi.station.webui#166]
At least 10px to the left and right sides. 15px would be even better.

![Screenshot 2022-04-28 at 9 32 47](https://user-images.githubusercontent.com/19531763/165691565-890e2e28-ec5f-447e-83cb-073561bb9778.png)

**Comment by laurijamsa** [comment]
I cannot see the padding in production:

<img width="226" alt="image" src="https://user-images.githubusercontent.com/1311912/167102786-9ac9e971-8b7a-46c3-9ea6-a168cae5a818.png">

...and actually not in the dev server either:

<img width="242" alt="image" src="https://user-images.githubusercontent.com/1311912/167102890-6dacb6e3-fc73-48de-ae38-781cafe334c0.png">

I am pretty sure I tested this well enough, but seems that I didn't :)
