### ISSUE TITLE
One-day data may be cached with missing pieces

### ISSUE THREAD

**Issue by ojousima** [ruuvi/com.ruuvi.station.webui#168]
Reported by @ZeroOne3010:

A sensor with one day data is missing a section:
![image](https://user-images.githubusercontent.com/2360368/169513333-e49e1e5f-11fe-44c0-bbd6-a35cef5c6809.png)

The same sensor shows the data in > 1 day view and on another browser. This is probably issue with caching.
![image](https://user-images.githubusercontent.com/2360368/169513588-ce68406b-5b48-4753-9e36-af49ec1c7238.png)

![image](https://user-images.githubusercontent.com/2360368/169513547-a7d8aaf1-bf35-4ae6-9775-431539a26a26.png)

**Comment by io53** [comment]
@ojousima this should be fixed. Can you confirm it?

**Comment by ojousima** [comment]
@io53 I don't know how to replicate this issue, but let's close it now and reopen if we get report of missing data. 

I haven't heard those reports in a while, so probably all good
