### ISSUE TITLE
sign in only shows top 1 or 2 pixels of email  v0.3.2

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.webui#173]
<img width="478" alt="signinTopsOffEmail" src="https://user-images.githubusercontent.com/2365961/172030899-fd17c198-d7a5-4c0e-845c-d460ea8dc8e2.png">

**Comment by io53** [comment]
The design is not done yet, it's just in dev to show the progress.

**Comment by DG12** [comment]
Works is webui  :-)
