### ISSUE TITLE
network error. v0.3.2

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.webui#174]
<img width="484" alt="networkerror" src="https://user-images.githubusercontent.com/2365961/172030958-c2aad0e5-ee19-43fb-9deb-9500a1dbbc2d.png">

immediately after email top dots only #173

**Comment by io53** [comment]
I cannot reproduce this. But nothing functionally has changed with the login in a long time so I'd guess that there was something in the email input that should not be there. Reopen this if you manage to get this happening in station.ruuvi.com
