### ISSUE TITLE
Caching is too optimistic

### ISSUE THREAD

**Issue by io53** [ruuvi/com.ruuvi.station.webui#178]
Large gaps in data can appear after a few months.
As reported by a user: In 3 months view (20.03 -> 20.06) data is missing data from 15.5 -> 10.6, but can be seen in 1 month view

**Comment by laurijamsa** [comment]
I couldn't test properly, but let's see if this helps. Ready to deploy.

**Comment by laurijamsa** [comment]
I'm not sure what's fixed, but I didn't notice issues. Ready to deploy in my opinion.
