### ISSUE TITLE
Not all dashboard blocks are resized equally

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/com.ruuvi.station.webui#180]
The bottom box is wider than the others:

![image](https://user-images.githubusercontent.com/1311912/175256483-65b6a649-9731-4488-a6a5-8c922b806f3d.png)

**Comment by io53** [comment]
The boxes has some wiggle room to make it look good with different sizes of screens (350 - 450px). This does have the side effect that a row with less boxes will be wider. I can investigate but I suspect that making the size match the smallest box might be tricky.
Making the boxes a fixed size could be a solution.
@sini-maaria do you have any ideas how to tackle this?

**Comment by io53** [comment]
Make dashboard cards align to the left
