### ISSUE TITLE
Zoom level is reset on auto refresh (on dark mode)

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/com.ruuvi.station.webui#184]
I noticed that user zoom level (if I zoom with mouse) is reset to default selection when the auto cloud database refresh triggered. This was on devstation.ruuvi.com/darkmode but when tried devstation.ruuvi.com I didn't see this same behaviour.

**Comment by io53** [comment]
I'll close this, /darkmode is slightly older. I will rebase it before next update and it'll be fixed
