### ISSUE TITLE
Dashboard time selector colors are wrong

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/com.ruuvi.station.webui#185]
May be some caching issue after trying dark theme but command+shift+r didn't help in this case:

<img width="606" alt="image" src="https://user-images.githubusercontent.com/1311912/175262439-f613d971-4531-4d5a-88ae-19f5e9390e66.png">

**Comment by laurijamsa** [comment]
Wrong also here:

<img width="460" alt="image" src="https://user-images.githubusercontent.com/1311912/175262956-6c5edca4-387f-451c-8473-e36f6e565929.png">

**Comment by io53** [comment]
@laurijamsa this only happens because you have visited the dark mode test version. If you go to the dark mode page and switch to light mode this should be solved. It's not something that will be an issue when the dark mode is published, only now when we are testing both versions at the same time

**Comment by laurijamsa** [comment]
Ah, ok. Then, I think we can close this. Noticed also this:

<img width="764" alt="image" src="https://user-images.githubusercontent.com/1311912/175264399-712f8b9b-4e16-47b9-86cc-85183bd8aa07.png">
