### ISSUE TITLE
Change font weight on dates dropdown

### ISSUE THREAD

**Issue by sini-maaria** [ruuvi/com.ruuvi.station.webui#186]
Let's have a normal font weight here instead of bold:

<img width="251" alt="Screenshot 2022-06-23 at 12 13 09" src="https://user-images.githubusercontent.com/19531763/175263489-1a35078b-dcbf-48e7-ab96-df4ae020860d.png">

**Comment by io53** [comment]
This is in /darkmode

**Comment by sini-maaria** [comment]
Looks good. Please fix also the font size to match with the smaller size.

<img width="334" alt="Screenshot 2022-07-06 at 13 06 02" src="https://user-images.githubusercontent.com/19531763/177526436-74ac4130-bbb7-4bcd-9f6b-c65b788032c6.png">
