### ISSUE TITLE
After selecting a longer history timespan, no new data is fetched

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/com.ruuvi.station.webui#188]
Maybe related to the https://github.com/ruuvi/com.ruuvi.station.webui/issues/175 (?)

See the video:

https://user-images.githubusercontent.com/1311912/176503451-03ec9595-383a-4b0e-92c7-ccb45019d08a.mov

**Comment by io53** [comment]
This was a bit tricky to debug as I didn't have the problem locally in the cache. But I think it is fixed now

**Comment by laurijamsa** [comment]
Seems to work on devstation but not on devstation darkmode. Ready to deploy I think.
