### ISSUE TITLE
Make dashboard load all latest data with one API call

### ISSUE THREAD

**Issue by io53** [ruuvi/com.ruuvi.station.webui#194]
/sensors-dense

**Comment by laurijamsa** [comment]
Seems to work!

Station (42 requests on 1min auto refresh):

<img width="1021" alt="image" src="https://user-images.githubusercontent.com/1311912/203677558-452fccd3-4c28-4684-9eb1-5229a884da94.png">


Devstation (2 requests on 1min auto refresh):

<img width="1021" alt="image" src="https://user-images.githubusercontent.com/1311912/203677375-69d3f71e-46e3-48c2-93f2-3a4110a22561.png">
