### ISSUE TITLE
Add home icon to main menu

### ISSUE THREAD

**Issue by sini-maaria** [ruuvi/com.ruuvi.station.webui#197]
Let's add a home icon to main menu:

DARK
Normal
<img width="388" alt="Screenshot 2022-07-11 at 10 02 29" src="https://user-images.githubusercontent.com/19531763/178207667-9a615467-fef9-4f6c-8b23-972fd7a5b3c8.png">

Hover: #1f9385
<img width="389" alt="Screenshot 2022-07-11 at 10 02 43" src="https://user-images.githubusercontent.com/19531763/178207755-3b49d243-fc01-4140-bd5c-b1f1c9e3d87f.png">

Active: 1f9385 **50%**
<img width="388" alt="Screenshot 2022-07-11 at 10 03 13" src="https://user-images.githubusercontent.com/19531763/178207793-ea19e6e4-0569-4249-8152-39568c9bc184.png">

LIGHT
Normal:
<img width="380" alt="Screenshot 2022-07-11 at 9 59 29" src="https://user-images.githubusercontent.com/19531763/178208141-60203c08-79dc-4812-869e-d9d39c6bb489.png">

Hover: #1f9385
<img width="382" alt="Screenshot 2022-07-11 at 10 01 40" src="https://user-images.githubusercontent.com/19531763/178208161-32f7c17a-e47c-4ad2-acb7-d32c25791d59.png">

Active: 1f9385 **30%**
<img width="385" alt="Screenshot 2022-07-11 at 9 58 39" src="https://user-images.githubusercontent.com/19531763/178208194-4fb36301-0d0c-49ad-b918-af71f2087b86.png">

**Comment by sini-maaria** [comment]
Arrows: #1f9385 on both themes.

**Comment by laurijamsa** [comment]
Let's consider this again if it's needed because Ruuvi logo already does the same?

**Comment by laurijamsa** [comment]
Let's close this one for now. I see no use for this icon because currently the Ruuvi logo does the same.
