### ISSUE TITLE
Move language selection under My account / Settings

### ISSUE THREAD

**Issue by sini-maaria** [ruuvi/com.ruuvi.station.webui#198]
Also, add a bit more space between the links.

<img width="381" alt="Screenshot 2022-07-11 at 10 25 41" src="https://user-images.githubusercontent.com/19531763/178210807-fb722986-4154-48c0-83e4-b2302a23a668.png">

**Comment by io53** [comment]
Change the language dropdown to radio group

**Comment by io53** [comment]
Dark/light mode toggle hover effect offset

**Comment by laurijamsa** [comment]
If I have a small browser window, I cannot see the language selection as the settings popup is not scrollable to high enough (centered somehow). However, I can scroll down, so scrolling is working:

<img width="1066" alt="image" src="https://user-images.githubusercontent.com/1311912/186584669-1018353b-0350-4528-aff4-016f5e07da66.png">
