### ISSUE TITLE
Add sensor sharing feature

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/com.ruuvi.station.webui#2]
Show also if a sensor is shared that who shared it with you.

**Comment by laurijamsa** [comment]
It is working but if I share to a new user and then trying to cancel the share before the new user logged in first time, I get this:

![image](https://user-images.githubusercontent.com/1311912/133555373-5ef358cc-a71e-48b7-b313-894fafaccf90.png)

**Comment by io53** [comment]
{
    "result": "error",
    "error": "User not found.",
    "code": "ER_USER_NOT_FOUND"
}

**Comment by io53** [comment]
Androids just shows "successfully shared" toast message. Maybe that's the way

**Comment by io53** [comment]
Show successfully share text on button until you type again
