### ISSUE TITLE
Add toggle button for background images to be shown on sensor cards

### ISSUE THREAD

**Issue by sini-maaria** [ruuvi/com.ruuvi.station.webui#202]
Let me know if something is unclear in this image.

![dashboard](https://user-images.githubusercontent.com/19531763/182345159-a3e66db8-5570-4626-8646-21c004540800.jpg)

**Comment by sini-maaria** [comment]
General:
- Make the button on top of image smaller (about 10-20 px smaller).

When no image:
- Show always the button with camera
- When hovering image area: change camera button to + button and text “Add image”

When image:
Show no actions on dashboard. Image can be changed on sensor page.

**Comment by sini-maaria** [comment]
This icon on toggle could be larger.

<img width="236" alt="Screenshot 2022-09-22 at 11 11 16" src="https://user-images.githubusercontent.com/19531763/191693760-84c53107-0edc-499a-92f0-1994b78abb2d.png">

**Comment by sini-maaria** [comment]
Can we fit 3 columns on this window size? The cards look somehow too wide.

Generally, padding between the cards could be smaller and it should be the same on all sides and same on all window sizes.

<img width="1536" alt="Screenshot 2022-09-22 at 11 14 05" src="https://user-images.githubusercontent.com/19531763/191694377-084ecf05-fc00-4438-a455-0eb3d974900e.png">

**Comment by sini-maaria** [comment]
Set max width for the content on mobile size card and next to it only the background color stretches.

<img width="535" alt="Screenshot 2022-09-22 at 11 24 28" src="https://user-images.githubusercontent.com/19531763/191696878-b585df6f-872a-4dcd-b62e-50d39e4490e6.png">

**Comment by sini-maaria** [comment]
This card is too wide, I'm sure we can fit 2-3 cards on this window size.

<img width="1021" alt="Screenshot 2022-09-22 at 11 26 15" src="https://user-images.githubusercontent.com/19531763/191697146-8edfae19-ea4b-4c80-b4d0-dd3501732737.png">

**Comment by sini-maaria** [comment]
> Can we fit 3 columns on this window size? The cards look somehow too wide.
> 
> Generally, padding between the cards could be smaller and it should be the same on all sides and same on all window sizes.
> 
> <img alt="Screenshot 2022-09-22 at 11 14 05" width="1536" src="https://user-images.githubusercontent.com/19531763/191694377-084ecf05-fc00-4438-a455-0eb3d974900e.png">

Edit. This is fine when image is visible but when you toggle "no image" there should fit 3 columns.

**Comment by sini-maaria** [comment]
On small card, make the circle smaller and remove text.

<img width="550" alt="Screenshot 2022-10-05 at 9 54 12" src="https://user-images.githubusercontent.com/19531763/193999789-7b794ea1-2ef4-4e76-b8c7-5f3adec1d31a.png">

**Comment by sini-maaria** [comment]
We should fit as many cards on the screen as possible:

<img width="1200" alt="Screenshot 2022-10-05 at 10 15 40" src="https://user-images.githubusercontent.com/19531763/194002759-4fd36338-76e4-4bb2-8707-506f494d4fab.png">
<img width="874" alt="Screenshot 2022-10-05 at 10 15 53" src="https://user-images.githubusercontent.com/19531763/194002765-d790fe8d-6c44-443a-8792-7afba8e3f301.png">
<img width="1199" alt="Screenshot 2022-10-05 at 10 16 04" src="https://user-images.githubusercontent.com/19531763/194002771-76af5985-7fac-4402-86b4-1b25af5e1942.png">
<img width="625" alt="Screenshot 2022-10-05 at 10 17 29" src="https://user-images.githubusercontent.com/19531763/194002774-2f798988-d25e-4c7c-8e82-5a293e94d471.png">

**Comment by io53** [comment]
Make dashboard card padding smaller on mobile (eq to padding on the sides)
Allow tag name to wrap to 2 lines on mobile dashboard cards with image (reduce main stat bottom padding and increase height if needed)
Add "..." on large/graph dashboard cards if name does not fit
Simplify graph/image button tooltip
Reverse graph/image button icon

**Comment by sini-maaria** [comment]
1. Leave the empty space (to fit the second row) under the large measurement numbers rather than under the title.
2. Add a bit more line height for the sensor name.
3. Make the "updated" text smaller on every screen size. Then you can reduce the height of the card a bit, at least on small screens.

<img width="613" alt="Screenshot 2022-10-17 at 9 56 35" src="https://user-images.githubusercontent.com/19531763/196109291-cd14b9cb-c84a-46dc-98f5-2c81f456a4e5.png">

**Comment by sini-maaria** [comment]
Also, this is happening on mobile size:
<img width="378" alt="Screenshot 2022-10-17 at 10 01 28" src="https://user-images.githubusercontent.com/19531763/196110112-4829a7ae-d53b-473d-b800-f4b93d537e84.png">

Btw, it seems that on my browser window the smallest card size fits to 380 px view. Is that small enough or should we reduce the min-width of the cards? The content could fit to card size that is 20-30 px smaller.
