### ISSUE TITLE
Show alarm limits on graph

### ISSUE THREAD

**Issue by io53** [ruuvi/com.ruuvi.station.webui#204]
Description:

Show alert limits in graph for the chosen graph history.
Toggle to show or hide limits from view.

Design to be confirmed with Sini-Maaria

![Image](https://user-images.githubusercontent.com/50437378/235572111-fdf39673-bfbf-4a62-8abf-e484f89add34.jpg)

**Comment by sini-maaria** [comment]
Here is an idea we could try. I will also design a toggle button for the alert view.

![Image](https://github.com/ruuvi/com.ruuvi.station.webui/assets/19531763/997d9f1e-0721-4120-802f-537fc0de2e29)

**Comment by markoaamunkajo** [comment]
@io53 can start implementing, ask Sini-Maaria about the toggle design.

**Comment by sini-maaria** [comment]
Color codes:

BG: 50%, #ff954d
Line:  #f15a24

![Image](https://github.com/ruuvi/com.ruuvi.station.webui/assets/19531763/b8341f51-bde4-46f7-9c69-f55af1e99399)

**Comment by markoaamunkajo** [comment]
Alert limit not show  correctly for pressure

**Comment by markoaamunkajo** [comment]
Looks like alert area is not filled correctly

![Image](https://github.com/ruuvi/com.ruuvi.station.webui/assets/50437378/ceaca9c5-194d-4fd5-a01e-3f5da7bf4c9e)

**Comment by markoaamunkajo** [comment]
@io53 the issue still persists on Mac Chrome, other browsers handle this correctly. This is visible on dashboard view as well.



![Image](https://github.com/ruuvi/com.ruuvi.station.webui/assets/50437378/ba1ba73f-b159-4357-974b-4c07437ff9d9)

**Comment by sini-maaria** [comment]
- Try 80% opacity on graphs.
- Use the same alert color on numbers.

![Screenshot 2023-06-27 at 12 47 17](https://github.com/ruuvi/com.ruuvi.station.webui/assets/19531763/4c39330a-5ab2-4626-9a5c-ac1f9cb72a60)
![Screenshot 2023-06-27 at 12 47 26](https://github.com/ruuvi/com.ruuvi.station.webui/assets/19531763/98cc830d-0c18-4fb0-ba2b-d65f1854c633)

**Comment by markoaamunkajo** [comment]
@io53 here are the colours for you to check

**Comment by markoaamunkajo** [comment]
@io53 

Comment from Sini-Maaria:
"This could be tested with the same color as the orange on the graphs."

![Image](https://github.com/ruuvi/com.ruuvi.station.webui/assets/50437378/dae27289-56e3-4cbf-98fe-e55747d3b1e5)

**Comment by markoaamunkajo** [comment]
QA passed for me
