### ISSUE TITLE
Compare sensors

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/com.ruuvi.station.webui#209]
Create a totally different "layer view" page where user can select multiple graphs on top of each other etc.

Ideas:

Combine 2 Y axis on top of each other, this way we can show 2 sensors info in one graph
Combine multiple physical sensors into one graph, showing single sensor ie temperature

Probably all these infos should be visible in the full screen mode so that user can switch between the values and timespan:

<img width="1409" alt="image" src="https://user-images.githubusercontent.com/1311912/186637358-7c6458a0-6483-4fdd-ab74-b94833bcbe34.png">

**Comment by markoaamunkajo** [comment]
Check ie Grafana

**Comment by markoaamunkajo** [comment]
We could show 2 sensor values in same graph ie temperature, humidity

![Image](https://user-images.githubusercontent.com/50437378/235568216-8121e9bc-fb3e-4384-a658-cd08365a61f6.png)

**Comment by markoaamunkajo** [comment]
![Image](https://github.com/ruuvi/com.ruuvi.station.webui/assets/50437378/3787ef7a-74f2-482e-a6c3-35cbcc24d12b)
![Image](https://github.com/ruuvi/com.ruuvi.station.webui/assets/50437378/216a88a6-d717-40a6-a624-62e6ba749e70)

Export options:

Create comparison files in the following way:

Selected sensor devices, selected unit
Discard other irrelevant information from csv and xlxs files (only selected will be added to file)

Generate CSV and Excel in following way:


![Image](https://github.com/ruuvi/com.ruuvi.station.webui/assets/50437378/eb8619d4-5940-450b-b5a4-ebe5fe7504c3)

**Comment by markoaamunkajo** [comment]
@io53 please check that the comparison graph is looking same as on normal full sensor page including

- chart only shows horizontal lines
- timestamps and date colouring follows theme

**Comment by sini-maaria** [comment]
Layout suggestion and colors for the chart:

#01b9a8
#e5d16e
#f77a61
#d62bb6
#9f2be2
#5273e8
#82d182

![Image](https://github.com/user-attachments/assets/38cced62-bce2-4f0c-8147-b2da751a3bb9)
![Image](https://github.com/user-attachments/assets/1c7ef8cb-edaf-4741-bcba-64925c689633)

**Comment by markoaamunkajo** [comment]
@io53 the date range selector and selecting range from dropdown apparently breaks loading the comparison chart. I am forever stuck in loading content.

**Comment by markoaamunkajo** [comment]
@io53 please remove Compare button from mobile view, it's unnecessary.

**Comment by markoaamunkajo** [comment]
@io53 also seems that with my Samsung S22 Ultra/Chrome browser it's not possible to pick 3 years from dropdown, it's simply not shown.  I think this is probably due to slightly scaled font that is used.

https://github.com/user-attachments/assets/39c72afd-c2a4-448c-b8b3-18290dbb5fb8

**Comment by markoaamunkajo** [comment]
On the compare page the unit selection should be actually something user can select/switch after sensor data has been downloaded. All data is downloaded now but if I want to change unit, I need to download everything again so it should be instead  a dropdown menu next to the date selector, same way as on the dashboard.

**Comment by markoaamunkajo** [comment]
A refresh button (or actually to make the load button to work again) would be needed. I would like to refresh the data but cannot, nothing happens if I press again the button. and if I refresh the page, it forgets what sensors I wanted to inspect, everything is cleared.

**Comment by markoaamunkajo** [comment]
@io53 let's move the unit selector next to date range selector on top of the cart view as discussed on the channel.

**Comment by markoaamunkajo** [comment]
@io53 we want to improve strings in this:

![Image](https://github.com/user-attachments/assets/7c0b0127-f429-414e-9909-adf97fb61643)

To this:

![Image](https://github.com/user-attachments/assets/d0e817d1-d7b3-40a6-8c3d-7eed8e4c3f65)


Looks like in localisation file this is used elsewhere so possibly need to make new ones.

**Comment by markoaamunkajo** [comment]
Looks like Load button is maybe hardcoded, I don't see it in language file.
I would like to change button text to Compare.

**Comment by markoaamunkajo** [comment]
@io53 zoom gesture on mobile doesn't work for me for compare sensors chart.

https://github.com/user-attachments/assets/2ab7d0b5-a5cf-47e8-a7da-65013a115423

**Comment by markoaamunkajo** [comment]
@io53 Strange bug with zoom when I change between unit views. I think instead of pressure I am shown battery scale on Y axis

https://github.com/user-attachments/assets/024d95f6-4b7b-457b-a780-6465d34667fc

**Comment by markoaamunkajo** [comment]
Looks like this is not actually compare sensors specific, I opened another card to investigate about this, so ignore comment on this card.

**Comment by markoaamunkajo** [comment]
@io53 please make buttons not hardcoded, add strings to localization file instead
