### ISSUE TITLE
mouse over Ruvvi logo cursor is pointer but no link - nit

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.webui#211]
hovering the mouse at just the right spot just below the Ruuvi logo changes the cursor to 'pointer' . see attached

![ruuviWebuipointer](https://user-images.githubusercontent.com/2365961/187734591-91395926-5003-417e-aa3f-1b62a18541fa.jpg)

![ruuviWebUIlink2](https://user-images.githubusercontent.com/2365961/187734577-c426c408-6617-4d67-8711-b83e4c0e370c.png)

**Comment by io53** [comment]
All of the logo should have the pointer cursor as it's a link that goes back to the dashboard. 
It took me a while to figure out what's going on here. It's the new Mac feature "Live Text" where you can select text from an image! 
Good find, but not much can be done about that.
