### ISSUE TITLE
Add support page link to the footer

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.webui#212]
It would be helpful if there was a [help] button.

**Comment by laurijamsa** [comment]
Yes, the support page link could be added on the bottom. My quick suggestion:

<img width="914" alt="image" src="https://user-images.githubusercontent.com/1311912/194497242-a751e2e1-b30a-41ca-9ab3-08b0edbe147c.png">

Assigning to S-M to finish the spec.

English string: "Support Page" and link https://ruuvi.com/support
Finnish string: "Tukisivu" and link https://ruuvi.com/fi/tuki

**Comment by sini-maaria** [comment]
> <img alt="image" width="914" src="https://user-images.githubusercontent.com/1311912/194497242-a751e2e1-b30a-41ca-9ab3-08b0edbe147c.png">

This looks ok, just make the line-height smaller and use our link styles.

**Comment by laurijamsa** [comment]
Cannot test in Finnish if the link is correct (ruuvi.com/fi/tuki) because the settings page is broken right now but if it is, ready to deploy.
