### ISSUE TITLE
connection aka signal alert not available - v0.3.6 

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.webui#214]
The setting for connection(IOS)  /  Signal Strength (RSSI) (android) is not available on webgui.
This is helpful when a ruuvi tag comes in or goes out of range.

**Comment by io53** [comment]
You mean in/out of range alerts? It's a nice idea but would need to be implemented in the backend. You could get unexpected alerts if the tag would be in range of someone else gateway tho 😅.

I'll close this and you can open an issue on the backend side instead.

**Comment by DG12** [comment]
As the Android / IOS already supports RSSI out /in range webui needs to be updated to support this.
Please reopen

**Comment by io53** [comment]
iOS does it by being connected to the tag, Android does it with foreground/background scanning. The web ui cannot do anything in the background so the feature need to be supported by the backend to make sense.

**Comment by DG12** [comment]
Values are written to the log exported by webui :-)

**Comment by DG12** [comment]
This also prevents disabling previously set alerts
