### ISSUE TITLE
Show min/max/average of the visible zoom timespan

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/com.ruuvi.station.webui#219]
Something like this:

<img width="1172" alt="image" src="https://user-images.githubusercontent.com/1311912/190852085-fc9563a6-5437-4190-85f3-e4f3495a2740.png">

Show them even if user isn't hovering on top of the graph. Note that the average calculation has to take into account if some data points are missing.

**Comment by DG12** [comment]
Looks like a LOT of data points. More than one or two per pixel. Things get slow. :-)

**Comment by io53** [comment]
> Looks like a LOT of data points. More than one or two per pixel. Things get slow. :-)

How can you tell that there is more data than the screen can show? It's not rendered 😅
The graph lib handles loads and loads of datapoints with ease. Resizing is a bit intense tho, but thats another topic :).

**Comment by DG12** [comment]
Rotating is also intense.

When stretching the graph very wide datapoints present are apparent.

**Comment by io53** [comment]
Todo:
- Add info button to the right of min/max/avg
- take zoom into account when calculating stats on data in the graph view, not all data loaded.

**Comment by markoaamunkajo** [comment]
@io53 using same card for improving the mobile view with cramped average as in screenshot

![cramped_mobile_iphone_chrome](https://user-images.githubusercontent.com/50437378/227113908-33147823-f456-4873-b274-9fc305539942.jpg)

**Comment by DG12** [comment]
"Time: 2023-" seems unnecessary.
 ":00" seconds unnecessary too?
Average could be "avgl"
