### ISSUE TITLE
Manually claim RuuviTags by MAC addresses

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.webui#223]
User has Ruuvi Tag(s) located remotely.
I wld be good if there was an option to add them by entering the MAC address.

**Comment by markoaamunkajo** [comment]
Description:

User will be able to  add sensor with MAC address, we only support adding 1 sensor at the time
Add button

- Sensors menu : Add a New Sensor
- Open Add a New Sensor in a popup


![Image](https://user-images.githubusercontent.com/50437378/235036454-15a78ac6-70a1-4264-a878-4c89f595ba05.png)
![Image](https://user-images.githubusercontent.com/50437378/235036455-79297237-281d-499e-91ae-79ad33397dc3.jpg)

**Comment by markoaamunkajo** [comment]
We should probably adjust in web that if sensor is added with MAC address it should add Ruuvi xxxx as name

**Comment by markoaamunkajo** [comment]
QA passed
