### ISSUE TITLE
Make all button an icon colors the same

### ISSUE THREAD

**Issue by sini-maaria** [ruuvi/com.ruuvi.station.webui#225]
So, to simplify things, this is what we agreed on Android mobile:

All buttons and icons: #35AD9F
All buttons pressed: #1F9385

No matter light or dark.

**Comment by sini-maaria** [comment]
For example:

<img width="858" alt="Screenshot 2022-10-05 at 10 03 59" src="https://user-images.githubusercontent.com/19531763/194000478-0a6f282b-b2ea-42f5-895a-08f041bb2d13.png">

**Comment by laurijamsa** [comment]
I may have missed some places where these were modified so test wasn't 100% good, but let's deploy anyways.
