### ISSUE TITLE
Enhance zooming on mobile

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/com.ruuvi.station.webui#229]
Make it possible to zoom x and y axes separately by pinching them. Now when I try to zoom in x axis for example, also y is zoomed in.

**Comment by markoaamunkajo** [comment]
@io53 I'm not sure if this serves any special purpose to be able to zoom far out 🥴
On mobile apps this is limited

Not 100% about logic but I think max and min available measurement in history


https://user-images.githubusercontent.com/50437378/227111721-4c9bb92b-2fec-4149-a5d3-af56fc2acf14.mp4

**Comment by laurijamsa** [comment]
I think zooming on mobile is now much better than before. I see some glitches but I think this is ready to be deployed as it is and we can possibly make it even better later on.
