### ISSUE TITLE
Don't show "narrow" graph when user has no image - improvment -

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.webui#230]
the wider version of the graph should be shown when there is no user provided photo.

![image](https://user-images.githubusercontent.com/2365961/194591362-657c0579-f6bf-49ac-b513-cf77e8b42550.png)

Should be:

![image](https://user-images.githubusercontent.com/2365961/194592557-93afc1d4-f18c-40fa-807b-df5ac9e95f4f.png)

**Comment by laurijamsa** [comment]
It's according to the design and we're not going to update the design right now. If user has no background images, an empty slot will be shown with a camera icon that encourages user to add a background image.

Feel free to open a new feedback topic about this for voting: https://f.ruuvi.com/c/r/feature-requests-voting/66
