### ISSUE TITLE
Make graph y-axis minimum range +-0.5

### ISSUE THREAD

**Issue by io53** [ruuvi/com.ruuvi.station.webui#232]

**Comment by DG12** [comment]
Please expand on this.

There is a big variation for rane and y-axis tics  between
 temperature,
 humidity and 
<pre>
air pressure   ( range for a particular sample )
uinits range:     tic marks                :: delta
hpa 99.75 to 100.15 :99.750, 99.800, 99.850:: 0.05
pa  997 to 1005     :997,998,999.          ::   1
mmHg 748 to 751     :748,748.5,749.        ::   .5
</pre>
setting a global attribute might not be effective

**Comment by io53** [comment]
The +-0.5 comes from the android app, but that only shows temperature, humidity and pressure graphs. Let's see how it goes
