### ISSUE TITLE
Stop using the original sign in page

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/com.ruuvi.station.webui#234]
Seems that the ruuvi.com/station (and ruuvi.com/fi/station) are working okay so it's time to stop using the original station.ruuvi.com sign in page. We need to:

1) redirect station.ruuvi.com to ruuvi.com/station (what's the best practice to do this?)
2) forward to ruuvi.com/station when user manually signed out if any other than Finnish language was used and to ruuvi.com/fi/station if Finnish language was used
3) something else?

**Comment by io53** [comment]
Note: You can still use the old login page by adding ?loginmethod=legacy to the url

**Comment by laurijamsa** [comment]
I don't think that this redirecting set up is what we're looking for. If I open an incognito window and visit devstation.ruuvi.com, the browser loads and shows the old page to me and after fully loaded, then it forwards me to ruuvi.com/devstation. 

https://user-images.githubusercontent.com/1311912/212079628-8e771613-27dc-4a64-ac5b-94fea4c9e771.mov

**Comment by laurijamsa** [comment]
When signing out, I can see the old sign in page for ~5 seconds until the redirect happens. Let's make it not to be shown at all if possible.

**Comment by laurijamsa** [comment]
Now it is fast for me too. Ready to deploy.
