### ISSUE TITLE
Add sensor selection for the graph view on dashboard

### ISSUE THREAD

**Issue by sini-maaria** [ruuvi/com.ruuvi.station.webui#248]
From this menu you can choose which sensor shows on the graphs on all cards.

![Screenshot 2022-11-03 at 14 37 49](https://user-images.githubusercontent.com/19531763/199722228-8fecaf41-a974-4c52-b56c-32d44de67c22.png)

**Comment by io53** [comment]
Change main stat on card to selected graph type, remove voltage and show temperature instead if something else than temp/humid/movement is selected.

Add "..." to graph type dropdown where the text is too long.
