### ISSUE TITLE
Sensor info is empty when chart range has no data

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.webui#25]
Description:

User has sensor with data for default timeline viewing range and it shows sensor information
He then selects different shorter range that has no data
Actual: sensor info is now empty
Expected: show sensor info

![Screenshot 2021-08-16 at 21 47 19](https://user-images.githubusercontent.com/50437378/129583047-a9ca1e77-ad9d-4969-afdb-5b3cb1f53217.png)

**Comment by io53** [comment]
I replaced the graph with some text, it can be edited here https://github.com/ruuvi/station.localization/blob/dev/station.localization.json#L6238
"No data for this time range"

**Comment by markoaamunkajo** [comment]
QA passed
