### ISSUE TITLE
No sensor data is cached

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/com.ruuvi.station.webui#258]
Has it been always like this? If I toggle between two sensors, full history is downloaded each time again and again and nothing seems to be cached.

Video:

https://user-images.githubusercontent.com/1311912/205531447-c88ea6ba-6d19-4774-9198-d00eded6b5bb.mov

**Comment by markoaamunkajo** [comment]
Looks like still same, not sure if this has something to do with what Otso was fixing yesterday.

I see history chart loaded if I choose timeframe between 2 hours and 6 months in this view.

**Comment by laurijamsa** [comment]
https://github.com/ruuvi/com.ruuvi.station.webui/assets/1311912/fa9d0ad9-687a-44b8-9ce6-324f305faa74

Sometimes history data is not downloaded or shown fully even user refreshes the view (I used Command + Shift + R) and several day gaps are visinble in the data.

**Comment by markoaamunkajo** [comment]
On prod.
