### ISSUE TITLE
What's new banner

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.webui#266]
Description:

Add what's new banner that will be shown after new web build was pushed that includes new features
To be used in major version updates to notify users about new features

In web need to be able to show banner about major version updates

--

If we change banner json after release to new id to tell user about new feature and point to changelog, and after 1 week we would revert back to original banner json that has old id, is it so that those users who have already closed that original banner they won't see it because the id is the same as original one?

**Comment by laurijamsa** [comment]
An idea:

![Image](https://user-images.githubusercontent.com/1311912/236975250-c3a7bbd1-e629-428d-894b-217e6364e41b.png)

**Comment by laurijamsa** [comment]
Elias confirmed in the meeting that the original banner won't be shown again to the user. So we can close this as we also decided that we won't need a more fancy what's new banner and we can use the current implementation for now.
