### ISSUE TITLE
Charts: indicate loading status in web app when prolonged loading is visible to user

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.webui#267]
Description:

When loading content into view takes long time it's sometimes confusing for user, for example loading 2 years chart history to view in detailed chart view.

Solution: show loading indicator during this time so user is aware.

https://user-images.githubusercontent.com/50437378/218616101-e6b4c4c2-bbdc-46e0-9b31-2a7b88cdfa41.mov

**Comment by io53** [comment]
overlay spinner on graph while loading data

**Comment by markoaamunkajo** [comment]
@io53 I'm not 100% convinced the loader is centered in mobile view. Please check.


![Screenshot_20230420_122344_Chrome](https://user-images.githubusercontent.com/50437378/233267895-59438f03-d4c0-4452-8ac2-4b56235b7ce2.jpg)

**Comment by markoaamunkajo** [comment]
QA passed
