### ISSUE TITLE
Fix login code issues when entered while holding shift

### ISSUE THREAD

**Issue by io53** [ruuvi/com.ruuvi.station.webui#268]

**Comment by laurijamsa** [comment]
I cannot reproduce this even on ruuvi.com/station so I cannot tell if the fix has any effect on the issue. Adding a ready to be deployed label anyways, because I assume you've tested it well and this is a relatively urgent thing to deploy soon.

**Comment by io53** [comment]
You can reproduce it by entering 3 characters, then in the last box just press shift.
