### ISSUE TITLE
Add CSV export

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.webui#27]
Description:

Web app is missing CSV export option. I think this would be super handy especially on web.

**Comment by laurijamsa** [comment]
We just discussed in a meeting that just a simple "export what you see" exporting feature would sufficient before we have a cloud support for full exports. But let's keep this in backlog until other more urgent features are implemented.

**Comment by io53** [comment]
This is a really simple task to implement. As long as we know how to present it nicely 😅

**Comment by laurijamsa** [comment]
Let's deploy together with the #80 and #81

**Comment by sini-maaria** [comment]
Remove background color hover effect on Export CSV. Add underline hover effect.

![Screenshot 2021-12-20 at 9 56 26](https://user-images.githubusercontent.com/19531763/146732307-cd479e70-adf8-4692-b94d-842d93b6e461.png)
