### ISSUE TITLE
Overview temperature graph missing temperature value in footing - 0.6.2 - visual

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.webui#271]
Graphs of all measurements always include

```
humidity%                        pressure

movements.                    temperature

nns ago
```

EXCEPT temperature graph

```
humidity%                        pressure

movements.                   

nns ago
```
This causes pressure to look like z-axis footing 
<img width="440" alt="tempGraphFootingMissingTemp" src="https://user-images.githubusercontent.com/2365961/221414056-b68f86e3-6002-49a4-ba0d-9064e58a12d1.png">

![image](https://user-images.githubusercontent.com/2365961/221414118-2c07a4a1-ae02-4eaa-9661-f11ce4ee351a.png)

**Comment by markoaamunkajo** [comment]
This is noted and will be fixed with a future task related to showing sensor values on cards in a new way
