### ISSUE TITLE
No graphs show. 2.0.0 (354) -defect 

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.webui#275]
No graphs show.
All sensors are present
![image](https://user-images.githubusercontent.com/2365961/222509188-d8fbbb77-ef07-4f73-9408-4f668d4e2b3f.png)

Upon further examination, 

![image](https://user-images.githubusercontent.com/2365961/222508946-27539edb-652e-408f-8616-666e90fbf2d0.png)

Is the fact that the amount is expired the reason?

**Comment by io53** [comment]
Free plan does not support graph history, this will be made clearer on the dashboard later. 
The plan expiry date did not show correctly for Free plan but an update was just pushed. Reload the page and it should show correctly :)

**Comment by DG12** [comment]
Very Poor user experience to show graphs with no data.

Your Ruuvi Cloud Free plan doesn't support history and email/push alerts. View plan comparison table on [cloud.ruuvi.com ⇗](https://cloud.ruuvi.com/). See also frequently asked questions: [FAQ ⇗](https://cloud.ruuvi.com/#faq).

IMHO  line break should be before "See also ...:

**Comment by DG12** [comment]
I was under the impression that free plan included 10 days of history
