### ISSUE TITLE
Add Simple view to WebUI

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.webui#276]
Description:

Web app is missing the "Simple view" option that we have in apps.
Please add this view and make sure it works also in mobile browsers.

<img width="324" alt="Screenshot 2023-03-03 at 10 08 58" src="https://user-images.githubusercontent.com/50437378/222621749-19a93c91-256c-481b-982f-1d5bbc397af3.png">

**Comment by laurijamsa** [comment]
If sensor name is long, other content cannot fit:

<img width="496" alt="image" src="https://user-images.githubusercontent.com/1311912/228734082-c6db0c12-8efe-40be-9752-b4a03eba96e8.png">

Probably easiest way is to shorten name with ... just like we're already doing here:

**Comment by io53** [comment]
Add Low battery indicator to history & graph view cards
Replace battery icon with the material ui icon.

**Comment by markoaamunkajo** [comment]
QA passed
