### ISSUE TITLE
Free mode: alerts in WebUI

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.webui#285]
Description:

When sensor is in Free mode user should not be shown alert notification colours or alert bells.
This is based on sensor, not based on account (account can have sensors that are under free or paid subscription).

User can adjust alert settings same as currently.

**Comment by io53** [comment]
@markoaamunkajo the colors for sensors where alerts are triggered are still there. Lets discuss and create a new tasks if that should be changed too.

**Comment by markoaamunkajo** [comment]
Let's discuss in meeting

**Comment by markoaamunkajo** [comment]
Agreed to show live alerts with colour, but not bells. This is considered completed.

**Comment by markoaamunkajo** [comment]
QA passed
