### ISSUE TITLE
Add languages to WebUI

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.webui#291]
Description:

Add existing languages to WebUI

French
German

**Comment by markoaamunkajo** [comment]
Investigate this issue and if it's possible to implement then can go forward.
We probably need some strings translated.

**Comment by io53** [comment]
Good find. "Calibrate" and "Clear" in the offset screen was hardcoded. The name dialog is not hardcoded, "Update" is correct for de according to the localization repo

**Comment by markoaamunkajo** [comment]
I think we use aktualisieren in de, changed with pull request.

**Comment by markoaamunkajo** [comment]
QA passed
