### ISSUE TITLE
Disable day selector in unsupported dashboard views

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.webui#294]
Description:

Please disable day selector in unsupported dashboard views
Image View
Simple View

**Comment by sini-maaria** [comment]
![Image](https://user-images.githubusercontent.com/19531763/233923853-26aef867-459a-4eab-b91e-5198f112dcc9.png)

**Comment by markoaamunkajo** [comment]
Looks like in image view actually selector is supported.
Now looks good to me.

**Comment by markoaamunkajo** [comment]
QA passed
