### ISSUE TITLE
Sensor Card Search

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.webui#295]
Description:

Add search for showing sensor cards in WebUI according to text search

- Search box at top of WebUI dashboard view:

Search box showing placeholder text "Search..." and magnifying glass icon
When user inputs text the magnifying glass changes to X
Tap on X will clear the text and search results

Make sure that the search box fits on mobile viewport
Optimise search to work in different dashboard views fast and efficiently

- Search logic:

User story:

User inputs text ie "cab" dashboard will automatically start showing only cards that contain the inputted text "cab"
Pressing enter deactivates the field but doesn't reset it. Keyword will be shown in field until cleared using X
Typical search wildcards and partials can be used
Other cards that are not matching search will be filtered out and not shown on dashboard
Dashboard selection will not reset search result (user can choose other view, other data or other day range) 
When user opens any card from search results in full sensor card view the search will not be reset, he should be able to return to search results after closing full sensor card view

![Image](https://user-images.githubusercontent.com/50437378/233921492-03573a1d-8baf-48a6-a763-ae132e1cb931.png)

![Image](https://user-images.githubusercontent.com/50437378/233921515-ee41b3c5-68de-46fa-84da-1eb806c38a6a.png)

**Comment by markoaamunkajo** [comment]
@io53

Magnifying glass is on top of menu, should be other way around

![Image](https://user-images.githubusercontent.com/50437378/235057504-7c7ad1e1-9211-4703-b165-ecf97512455e.png)


Seems that search terms are not limited to title, please limit to title only

![Image](https://user-images.githubusercontent.com/50437378/235057524-e60378a2-6242-4528-bf2d-ffc468c8c84d.png)

**Comment by laurijamsa** [comment]
We discussed in the meeting that also mac addressed can be searched, which
is a good feature I think. Probably these senaors have 9 in their
addresses?

**Comment by markoaamunkajo** [comment]
Ahh good point Lauri

**Comment by markoaamunkajo** [comment]
User makes search for "c"

Sensors are correctly listed with search but when user opens sensor card view and uses arrows to move between previous and next sensors the result is not respected.

https://user-images.githubusercontent.com/50437378/235567080-9c2bd265-3556-4cfa-b393-8f33d03e4226.mov

**Comment by markoaamunkajo** [comment]
QA passed

**Comment by sini-maaria** [comment]
![Image](https://github.com/ruuvi/com.ruuvi.station.webui/assets/19531763/3ca4143a-09f2-400a-bddd-32023c028ebd)

**Comment by markoaamunkajo** [comment]
QA passed
