### ISSUE TITLE
Change title in History view

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.webui#307]
Description:

Currently we show title "History" in full card view, let's change this to indicate which sensor is selected.

**Comment by laurijamsa** [comment]
Draft incoming

**Comment by markoaamunkajo** [comment]
This good @laurijamsa 
![Image](https://github.com/ruuvi/com.ruuvi.station.webui/assets/50437378/8d6c67c6-a74b-4e6e-9037-a50a058166bf)

**Comment by sini-maaria** [comment]
![Image](https://github.com/ruuvi/com.ruuvi.station.webui/assets/19531763/422844c0-9635-4883-ba1b-9a9d0e761765)

**Comment by markoaamunkajo** [comment]
@io53 the mobile view is currently not aligning as expected.

![Image](https://github.com/ruuvi/com.ruuvi.station.webui/assets/50437378/95ccabe0-eeab-4888-bdbb-e0f0dc940d42)
![Image](https://github.com/ruuvi/com.ruuvi.station.webui/assets/50437378/365e9eca-54ee-4b1c-870a-bd445549d791)

**Comment by markoaamunkajo** [comment]
@io53 let's organise this way
Notice the centered elements

![Image](https://github.com/ruuvi/com.ruuvi.station.webui/assets/50437378/9f7ab042-c96d-4982-97d4-a8bb6527c7a8)

**Comment by markoaamunkajo** [comment]
QA passed
