### ISSUE TITLE
Layout fixes for dashboard cards

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.webui#312]
Description:

**Comment by sini-maaria** [comment]
- Use the same padding for the menu dots as on the card title.
- Use this guide on all the views (simple, history, image)

![Screenshot 2023-06-01 at 8 15 15](https://github.com/ruuvi/com.ruuvi.station.webui/assets/19531763/edb31cf6-ff59-4b12-90a6-c76a7c49c716)

**Comment by sini-maaria** [comment]
Also, make the clickable area bigger when possible:

![Screenshot 2023-06-01 at 8 24 54](https://github.com/ruuvi/com.ruuvi.station.webui/assets/19531763/00926d2a-fc92-4e84-820e-4fcc37ffe028)

**Comment by markoaamunkajo** [comment]
QA passed
