### ISSUE TITLE
Remember selected dashboard view in WebUI

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.webui#313]
Description:

Remember selected dashboard view in WebUI

User story:

User selects a simple view in webUI and then logs out.
When he signs in again to webUI this view should be remembered.

Important! Don't sync this view selection with mobiles, webUI should work independently and not affect mobile view selection, that currently supports syncing views.

**Comment by laurijamsa** [comment]
We discussed this in our meeting and agreed that this would cause more issues than benefits.
