### ISSUE TITLE
Share  Sensors center

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.webui#317]
Description:

Share multiple sensors to users at once
This feature will be available to all subscription levels including free

- Share selected sensors to email addresses

Show share button as disabled before all required information is filled
If sensor already has full shares, show as greyed out, user cannot select it 
If user account has total share limit reached, then show all greyed out (but we will consider lifting share limit also so this will be rare case)

- Show shared sensors with email tag cloud, if user chooses X it will delete share
- Show pending shares sent, if user chooses X pending share will be deleted
- Show sensors shared to user, if user chooses X it will delete share

![Image](https://github.com/ruuvi/com.ruuvi.station.webui/assets/50437378/ad830a15-1e44-4d74-9880-ea45a7c23a94)

**Comment by markoaamunkajo** [comment]
Here is example of confirmation popup styling. Texts to be added.

![Image](https://github.com/ruuvi/com.ruuvi.station.webui/assets/50437378/4be0f135-d2f1-4415-9c79-06c379c42658)

**Comment by markoaamunkajo** [comment]
@io53 I just invented the email address sharesensor@ruuvi.com and shared my sensor to this email.
It should not show or count under active shares, since it's a pending share and afaik account doesn't exist yet.


![Image](https://github.com/ruuvi/com.ruuvi.station.webui/assets/50437378/4c7c5c5a-6f7d-4972-925e-3fc813c8f567)

**Comment by markoaamunkajo** [comment]
Sensors dropdown is too narrow

![Image](https://github.com/ruuvi/com.ruuvi.station.webui/assets/50437378/a2484dfa-e65d-4a7c-8736-fabebd56814b)

Colours are incorrect in dark mode, there is no box at the top area for sharing new sensor, like there is in light mode.

![Image](https://github.com/ruuvi/com.ruuvi.station.webui/assets/50437378/12de3001-e9ab-4277-93ac-a37aede6f6aa)

**Comment by markoaamunkajo** [comment]
Restylize sensor sharing remove confirmation to use a custom popup.
User should be able to select Remove and OK by pressing Enter on keyboard.
Add strings to language file.

![Image](https://github.com/ruuvi/com.ruuvi.station.webui/assets/50437378/a002bf21-a9b6-4a7a-9b63-4e6f303e3a81)

**Comment by sini-maaria** [comment]
1. Add padding
2. Background colour is the same as in 1 but opacity 50%

![Screenshot 2024-06-05 at 9 22 16](https://github.com/ruuvi/com.ruuvi.station.webui/assets/19531763/5482aa93-7728-4a9e-beaa-02fa971516a0)

**Comment by sini-maaria** [comment]
1. Add padding and border (Ruuvi button color). Doesn't have to be this wide.
2. Background: button color 20%
3. Background is the same as in Settings&Alerts
4. Add space here

![Screenshot 2024-06-05 at 9 49 33](https://github.com/ruuvi/com.ruuvi.station.webui/assets/19531763/82a2138e-304f-4383-bbb0-8f1b81d14155)

**Comment by markoaamunkajo** [comment]
QA passed

**Comment by markoaamunkajo** [comment]
Will mark as ready to deploy once #417 is completed too

**Comment by markoaamunkajo** [comment]
QA passed
