### ISSUE TITLE
Export options: CSV, XLSX, PDF

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/com.ruuvi.station.webui#323]
Description:

Allow exporting sensor history in csv, xlsx and pdf formats.
Change export button to menu named "Export..." and options CSV, XLSX, PDF

PDF: name of sensor, name of selected chart, selected chart as image, min/max/avg, improve styling according to Ruuvi layout after demo with Sini-Maaria
XLSX: can we use library that just converts csv to xlsx-format?

**Comment by sini-maaria** [comment]
![Image](https://github.com/ruuvi/com.ruuvi.station.webui/assets/19531763/a45e38f3-1d1c-4786-afa9-f45a71dec512)

**Comment by markoaamunkajo** [comment]
@io53 took 6 months report with csv and xlsx but for some reason start date is not same


[Ruuvi 97CB_20240226T145546+0700.csv](https://github.com/ruuvi/com.ruuvi.station.webui/files/14401404/Ruuvi.97CB_20240226T145546%2B0700.csv)
[Ruuvi 97CB_20240226T145504+0700.xlsx](https://github.com/ruuvi/com.ruuvi.station.webui/files/14401403/Ruuvi.97CB_20240226T145504%2B0700.xlsx)

**Comment by markoaamunkajo** [comment]
On prod
