### ISSUE TITLE
Offline alert

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.webui#324]
Description:

Offline sensor alert adjustment to be added under Alerts.
Delay set in minutes.

Can be implemented when API is ready.

This feature is available when subscription level is Pro or higher. If lower subscription level then show switch as disabled and show text that higher subscription level is required. (if shared sensor the owner must have pro or higher, sharee can then use the feature).

![Image](https://github.com/ruuvi/com.ruuvi.station.webui/assets/50437378/b9d56850-9b71-4fb3-864b-c56d95e959fd)

![Image](https://github.com/ruuvi/com.ruuvi.station.webui/assets/50437378/a7a934d9-149e-4890-981e-776c91923558)

![Image](https://github.com/ruuvi/com.ruuvi.station.webui/assets/50437378/05e9a906-a640-492f-a34b-1b1244f38506)

**Comment by markoaamunkajo** [comment]
@sini-maaria can you help to design the subscription level requirement when feature is not available unless your subscription level is specific, such as basic, pro etc.

**Comment by laurijamsa** [comment]
Let'd drop the red string completely and show this feature only to Pro or higher subscription level sensors for now.

**Comment by markoaamunkajo** [comment]
This from API

curl --location 'https://testnet.ruuvi.com//alerts' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer $BEARER' \
--data '{
    "type": "offline",
    "min": 0,
    "max": 600,
    "enabled": true,
    "sensor": "CD:F2:AA:36:F6:8B",
    "timestamp": 1688929700,
    "delay": 0
}'

**Comment by markoaamunkajo** [comment]
Please use this as title for popup:

Set cloud connection alert

![Image](https://github.com/ruuvi/com.ruuvi.station.webui/assets/50437378/97df8d32-2aa5-4d5c-b6c2-78deff820ed8)

**Comment by markoaamunkajo** [comment]
Language strings updated to language repository

**Comment by markoaamunkajo** [comment]
@io53 looks like title can go behind the "X" close icon. Let's make sure there is always space for that.

![Image](https://github.com/ruuvi/com.ruuvi.station.webui/assets/50437378/264c4c82-7ab5-4591-9e60-71799f2644f5)

**Comment by markoaamunkajo** [comment]
QA passed
