### ISSUE TITLE
Free account misleading  message "No data for this time period"

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.webui#329]
<img width="640" alt="NoDataButRecentAdvertisment" src="https://github.com/ruuvi/com.ruuvi.station.webui/assets/2365961/576f761f-9d92-4187-825b-3a2ed4ae1417">

**Comment by DG12** [comment]
Seems to be:  "Free account does not include ANY history"

Message should be changed.

**Comment by DG12** [comment]
Additionally, for free account:
A) history view should be disabled and
B) image view should have time dropdown disabled

**Comment by DG12** [comment]
C) After login free account should show simple view. (Current it displays image view.)

D) selecting a single sensor from the simple view should suppress:
D1) History
D2) zoom
D3) export CSV
D4) hours drop-down

**Comment by markoaamunkajo** [comment]
String for free sensors with no data was improved. Other suggestions considered at a later time.
