### ISSUE TITLE
Sensor background image

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.webui#33]
Description:

I can see some sensors have background pictures shown in avatar bubble.
It would be logical to have option to edit sensor background image.

Upload from device
Upload from camera
Remove

**Comment by io53** [comment]
Android resizes images to 960x1440, and iOS to 1080 × 1440. Web should resize to something similar

**Comment by laurijamsa** [comment]
Seems that the webui image upload thingy doesn't crop the image to a portrait image like I think the mobile apps do, but this is ok for now, because we'll possible have other ui updates coming that may define how we'll want to crop and resize bg images in the future. Ready to deploy.

**Comment by markoaamunkajo** [comment]
QA passed works for me well enough
