### ISSUE TITLE
CSV export time format should be ISO with timezone

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.webui#331]
Description:

CSV export time format should be ISO with timezone
Let's add this to the export filename as suggested below.

iOS card: https://github.com/ruuvi/com.ruuvi.station.ios/issues/1678
Android card: Android card: https://github.com/ruuvi/com.ruuvi.station/issues/1124

**Comment by markoaamunkajo** [comment]
Proposed idea.

![Image](https://github.com/ruuvi/com.ruuvi.station.webui/assets/50437378/ab336542-2596-4c78-8e09-fb40e7b28067)

**Comment by io53** [comment]
https://en.wikipedia.org/wiki/ISO_8601

**Comment by markoaamunkajo** [comment]
Filename example: Friiz_ 20230830-1249_+04:00

**Comment by markoaamunkajo** [comment]
QA passed
