### ISSUE TITLE
If no sensors, cannot add a sensor manually

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/com.ruuvi.station.webui#332]
If user's account has no sensors, the Sensors dropdown menu item is not shown and therefore user cannot add his/her first sensor manually. 

![IMG_20230627_101856_677.jpg](https://github.com/ruuvi/com.ruuvi.station.webui/assets/1311912/c292dba4-2d5c-483e-a17d-445dd7a44603)

**Comment by markoaamunkajo** [comment]
QA passed
