### ISSUE TITLE
Make the "No data" text more subtle on dashboard

### ISSUE THREAD

**Issue by sini-maaria** [ruuvi/com.ruuvi.station.webui#334]
- Mulish, bold
- 50 % #fff
- align left
- center vertically
- use the same padding on both sides

Text content should also be updated to include words "Ruuvi Cloud Free". @laurijamsa 

![Screenshot 2023-06-27 at 13 51 50](https://github.com/ruuvi/com.ruuvi.station.webui/assets/19531763/97d96c24-07d3-473a-84a9-28d4583da70c)

**Comment by markoaamunkajo** [comment]
Now it seems it's misaligned. Btw this text is shown in history view in my screenshot, maybe the alignment comes from there.

![Image](https://github.com/ruuvi/com.ruuvi.station.webui/assets/50437378/8332132d-71d6-43d0-ba04-53e84502812d)

**Comment by markoaamunkajo** [comment]
@io53 also light mode

![Image](https://github.com/ruuvi/com.ruuvi.station.webui/assets/50437378/6fff8c07-8b67-4bb1-9781-98f757901fcc)

**Comment by markoaamunkajo** [comment]
QA passed
