### ISSUE TITLE
Global settings popup not opening

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.webui#336]
Description:

If I scroll to settings (from three dot menu from dashboard and then try to open the real global settings popup, nothing happens, the url looks like "https://devstation.ruuvi.com/#/D7:ED:B5:24:39:C4?scrollTo=settings?settings?settings?settings"

**Comment by io53** [comment]
for me: branch is #338

**Comment by markoaamunkajo** [comment]
Surprise bug, now this has moved to My Ruuvi Account link.

![Image](https://github.com/ruuvi/com.ruuvi.station.webui/assets/50437378/694caf92-f9e6-4b8e-8379-2e5d6330d31e)

**Comment by markoaamunkajo** [comment]
QA passed
