### ISSUE TITLE
Language support for push messages and emails

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.webui#343]
Description:

User language to be saved and sent to cloud

Default language:
Operating system language (used as browser default)

Store language:
If profile has language different from browser language, then use profile language
Change profile language only if user manually changes it from settings
Store language setting to cloud automatically only if it doesn't exist yet

User stories:

User uses OS with language Finnish, browser uses default language Finnish.
He signs first time into Ruuvi Station Web - his profile doesn't have any language preference saved. Language is selected as Finnish and stored to cloud, because there was no previous setting stored.
Then user changes profile language in settings to French.
We will store language setting French to cloud.

Second user story:

Language German has been already stored to cloud previously (through other Ruuvi Station).
When user signs to Ruuvi Station Web and profile exists - Web profile will choose German.

We will send alert push messages and alert emails in language stored in cloud.

**Comment by markoaamunkajo** [comment]
To test: open station in 2 browsers and another with different language.

**Comment by markoaamunkajo** [comment]
Case 1:
marko+staging_free@ruuvi.com

user signed in on chrome mobile with OS/browser language Finnish
PROFILE_LANGUAGE_CODE="en"


Case 2:
marko+staging_basic@ruuvi.com

user signed in on chrome mobile with OS/browser language German
No language code found in profile

**Comment by markoaamunkajo** [comment]
Will run the tests with new profiles just in case and will ask Otso about results.

**Comment by markoaamunkajo** [comment]
marko+lang-test-de@ruuvi.com

Android Chrome broser, OS language and browser language set to DE

  First login, profile language code EN

So I consider this is not working correctly

**Comment by io53** [comment]
@markoaamunkajo are you sure it was the first login for that account from devstation? Tried to reproduce with chrome on android but it works just fine on my phone.

**Comment by markoaamunkajo** [comment]
@io53 we used devstation.ruuvi.com/staging for testing with Otso.
Is this the correct server to use?

**Comment by io53** [comment]
Yes, should work in both environments
