### ISSUE TITLE
UI Fixes

### ISSUE THREAD

**Issue by sini-maaria** [ruuvi/com.ruuvi.station.webui#35]
![Screenshot 2021-08-19 at 12 29 55](https://user-images.githubusercontent.com/19531763/130045379-6547fd10-a966-4c73-be22-60c6e1eb0ab4.png)

**Comment by sini-maaria** [comment]
A couple of changes to previous tasks:

1. Let's change the accordion title background to white. I realised they were white in the original file and that looks better.

<img width="1081" alt="Screenshot 2021-09-09 at 9 21 13" src="https://user-images.githubusercontent.com/19531763/132633543-2332e984-d082-4c40-b9f6-7bf28e30849b.png">

2. Let's remove slider indicator "30" here:

https://user-images.githubusercontent.com/19531763/130655055-255ad057-0def-4616-8449-0f887bc972b6.png
<img width="995" alt="Screenshot 2021-09-09 at 9 17 20" src="https://user-images.githubusercontent.com/19531763/132633712-e688ac4a-0fdc-49ff-9b3f-900d97e0a494.png">

**Comment by sini-maaria** [comment]
Please fix these aswell:

Graph bg: #44c9b9, 30%
Graph border/line: #44c9b9
Font size: 12px
Thin lines behind the graph: #d4ede8, 50%
(Please use this #d4ede8 as line color throughout the site.


<img width="531" alt="Screenshot 2021-09-09 at 20 31 25" src="https://user-images.githubusercontent.com/19531763/132734261-764ccca1-32a1-4fff-b940-783280fa4c95.png">

**Comment by DG12** [comment]
Please consider minor changes in positioning of name and temperature etc, i.e. adjacent rather then above/below would allow default screen to show 6 complete tags
See attached
<img width="640" alt="minorPositionChangeRequest" src="https://user-images.githubusercontent.com/2365961/132934027-e25f8e2a-f926-478d-bae4-cadf15fdd426.png">

**Comment by laurijamsa** [comment]
> Please consider minor changes in positioning of name and temperature etc, i.e. adjacent rather then above/below would allow default screen to show 6 complete tags
> See attached
> <img width="640" alt="minorPositionChangeRequest" src="https://user-images.githubusercontent.com/2365961/132934027-e25f8e2a-f926-478d-bae4-cadf15fdd426.png">
> 

This would probably make it look too tight and would limit the max length of sensor names even more. If your browser window is too small, you can zoom out the view by pressing the keys Command and -

**Comment by io53** [comment]
@sini-maaria what font & size should this one be?
<img width="147" alt="Screenshot 2021-09-11 at 10 32 05" src="https://user-images.githubusercontent.com/1242634/132940332-b48d6d22-ef78-4ce3-b5d9-5171679a8207.png">

**Comment by io53** [comment]
Should we remove decimals in graphs like it is in the UI design? In mobile the decimals is always showing

**Comment by DG12** [comment]
@lauri   ⌘- works on Mac book pro but  ... second row still has hPa and times cut off.
Maybe just reduce the distance above graph and is that line below the graph necessary
<img width="1280" alt="webuiTruncatesBottom" src="https://user-images.githubusercontent.com/2365961/132961084-ccd87c24-a791-49c5-ad59-f861d78d838c.png">

by the way "Ruuvi C85E at Gornell's" 
renders "RUUVI C85E AT GORNEL..." on iPhone , even when held in landscape!  Issue#147

**Comment by DG12** [comment]
Should the rUUVi icon be at the top of the screen ? also in the TITLE ?

**Comment by DG12** [comment]
On a detail,  clicking dropdown to show (last) 2 days X axis labeling only shows mm/dd (oops I mean dd/mm).
 In one case 9/9 9/9 9/9 10/9 10/9 ... 10/9 10/9 11/9 11/9 11/9...

Should the last update "2 Min 40 s ago" be suppressed?

I think this might be hard:

BUT,  mouse select  to see only 1 hour legend still says "last 2 days" and 10/9 is repeated on the x-axis

**Comment by sini-maaria** [comment]
> @sini-maaria what font & size should this one be?
> <img alt="Screenshot 2021-09-11 at 10 32 05" width="147" src="https://user-images.githubusercontent.com/1242634/132940332-b48d6d22-ef78-4ce3-b5d9-5171679a8207.png">

It's the same as "liikettä" in the same picture. 50% opacity.

**Comment by io53** [comment]
dashboard cards add 2x padding
