### ISSUE TITLE
Add deep linking support

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.webui#359]
Description:

Please add deep linking support for apps.

Email contains url that user opens, in format (example) station.ruuvi.com/mobile/
Open dashboard view in app if app is installed on this mobile
If not installed take to app store / play store

Discuss on channel about details with developers when implementing

**Comment by io53** [comment]
Navigating to /dashboard on mobile should open appstore/playstore, if app deep linking is supported on the app it should just open the app.
On desktop is should just redirect to /

**Comment by markoaamunkajo** [comment]
QA passed
