### ISSUE TITLE
temp no data no graph, humidity without data with graph, temp graph shows data

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.webui#361]
for D3:51:78:72:EC:0F (aka turtle)
A) Looked at the temperature for 1 week: " no history data" although last update was 2days 5h ago.
B) looked at humidity: graph is shown  but no lines
C) locked back at temperature: SHOWS GRAPH
See screen shots attached notice times.
<img width="1352" alt="turtle_1649-231003A_temperature" src="https://github.com/ruuvi/com.ruuvi.station.webui/assets/2365961/b9c2a312-294e-44de-81b9-c4ade7f7204f">
<img width="1352" alt="turtle_1650-231003_Humidity" src="https://github.com/ruuvi/com.ruuvi.station.webui/assets/2365961/5efc4914-0d5c-42c9-844c-b12b0fc4418a">
<img width="1352" alt="turtle_1651-231003B_temperature" src="https://github.com/ruuvi/com.ruuvi.station.webui/assets/2365961/ef7b2e8c-00ca-4e3c-a032-03e111587be2">

**Comment by markoaamunkajo** [comment]
ECOF turtle eggs looks like broken 326F = 163C , which in data format is not available, we have one case with Lauri that has this behavior too.

Other points to be taken:

Single datapoints not shown on chart, we will improve that on separate card.
