### ISSUE TITLE
Add View menu to WebUI

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.webui#367]
Description:

This will replace the current Image View / History View / Simple View selector

Add View menu that includes the following:

**Card Type**
Image cards
History cards
Simple cards

- Use highlight when card type is selected, same as elswhere in menu items

**Ordering**
Reset to alphabetical sorting

- This item is shown only when custom card ordering is used. Hide title and item when alphabetical ordering is used

- When selected, show popup.

Popup:

Are you sure?

Are you certain you wish to revert the sensor card ordering to alphabetical sorting?

Cancel, Confirm

**Comment by markoaamunkajo** [comment]
QA passed

**Comment by io53** [comment]
cancel is not translated

**Comment by markoaamunkajo** [comment]
QA passed
