### ISSUE TITLE
Show correct confirmation messages when removing a sensor

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/com.ruuvi.station.webui#37]

**Comment by markoaamunkajo** [comment]
![Screenshot 2021-09-09 at 9 09 46](https://user-images.githubusercontent.com/50437378/132610619-a6b44072-3aa7-42f8-a609-a1dc5df5f4b9.png)

Popup title and buttons are in English, content in Finnish.

**Comment by io53** [comment]
@markoaamunkajo no those are coming from the browser, if your browser would be set to Finnish it would be in Finnish.
We can change this to a custom dialog we implement the new renaming.
