### ISSUE TITLE
Log out user from app when token expired

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.webui#374]
Description:

When user confirms account deletion through email he is not currently logged out from Web app.

Expected:

Log user out in this case.

**Comment by io53** [comment]
Sign out if 401

**Comment by markoaamunkajo** [comment]
@io53 I'm testing this on staging but I am not getting account deletion success.


![Image](https://github.com/ruuvi/com.ruuvi.station.webui/assets/50437378/ce2dfa7e-9392-49c8-9407-af15b34edc4f)



![Image](https://github.com/ruuvi/com.ruuvi.station.webui/assets/50437378/6c7d4920-0c5f-4b35-b8e1-3dba2bf549f8)

**Comment by io53** [comment]
Huh, this work fine for me. Note if you are testing this task specifically, use https://devstation.ruuvi.com/staging

**Comment by markoaamunkajo** [comment]
Waiting for Otso to fix backend

**Comment by markoaamunkajo** [comment]
Tested again, not working I get same message. I have sensors on this profile.

**Comment by laurijamsa** [comment]
I will keep this issue open once tested one more time by Marko after holidays.

**Comment by ojousima** [comment]
Related Cloud task: https://github.com/ruuvi/ruuvi.cloud.js/pull/449

**Comment by markoaamunkajo** [comment]
Tested and worked on all platforms
