### ISSUE TITLE
Improve banner colours / features

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.webui#390]
Description:

Make it more easy on the eye

**Comment by markoaamunkajo** [comment]
![Image](https://github.com/ruuvi/com.ruuvi.station.webui/assets/50437378/a24d0c23-39cd-479e-84b5-b2311172546b)

**Comment by laurijamsa** [comment]
Could we just make the banner background color darker and then white text would be more readable? We don't have urgent needs for other updates I would say.

**Comment by sini-maaria** [comment]
![Screenshot 2024-04-09 at 14 01 00](https://github.com/ruuvi/com.ruuvi.station.webui/assets/19531763/ea6df5da-5250-4679-905a-8d04e5ca01ac)

**Comment by markoaamunkajo** [comment]
QA passed
