### ISSUE TITLE
Upgrade plan tag to free mode sensor cards

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.webui#392]
Description:

"No history data. This sensor is in Free mode. Upgrade Plan"

Upgrade plan tag will be a link to open to cloud.ruuvi.com on sensor cards that have this tag.

Link URL:
English, other languages: cloud.ruuvi.com
Finnish: cloud.ruuvi.com/fi

Dashboard (image card, history card)
![Image](https://github.com/ruuvi/com.ruuvi.station.webui/assets/50437378/c1284be4-7ad5-4466-8d8d-a66967b78901)

Full card:
![Image](https://github.com/ruuvi/com.ruuvi.station.webui/assets/50437378/7d4c3b71-df4d-4d71-a34d-ce7ac1c3e950)

**Comment by sini-maaria** [comment]
Let's modify the string so that it doesn't have two sentences.

New:
"There is no historical data because this sensor is in Free mode."
"Tämä anturi on Free-tilassa, eikä historiatietoja ole saatavilla."

When the sensor is shared, show text but no Upgrade button. This is because the sharee cannot upgrade the plan, because he doesn't own it.

**Comment by laurijamsa** [comment]
Alignment of the Update plan button in here does not seem quite correct. The Upgrade plan text looks also too big (or the button too small).

![Image](https://github.com/ruuvi/com.ruuvi.station.webui/assets/1311912/943cc6fd-d252-4b8a-aff0-4e4550aef297)

**Comment by markoaamunkajo** [comment]
QA passed

**Comment by markoaamunkajo** [comment]
@io53 now link is not shown on dashboard cards

![Image](https://github.com/ruuvi/com.ruuvi.station.webui/assets/50437378/1e6faeff-2e93-4e71-9163-dd3f2bfdde6b)

**Comment by markoaamunkajo** [comment]
Now shows on dashboard, will ask confirmation from @sini-maaria that this design is now good before marking as ready to deploy.

**Comment by markoaamunkajo** [comment]
Assuming this is done @io53
