### ISSUE TITLE
My Ruuvi Account text link style

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.webui#393]
Description:

Use same text link style on My Ruuvi account as in the example picture

![Image](https://github.com/ruuvi/com.ruuvi.station.webui/assets/50437378/98916f5a-099e-40ee-9c2f-f8c0ccb3762d)

**Comment by laurijamsa** [comment]
This needs a bit more more info. I see 4 hyperlinks in this popup:



![Image](https://github.com/ruuvi/com.ruuvi.station.webui/assets/1311912/048e31e6-1884-4aa1-b2d8-d578eaba1353)


Do we want to modify all of those somehow? Or can we just close this issue for now?

**Comment by markoaamunkajo** [comment]
Closing this task as we opted for button design
