### ISSUE TITLE
Show unavailable features greyed out and include Upgrade Plan link

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.webui#395]
Description:

Show all hidden features for all subscription levels, including Free.

Show features as greyed out, when users don't have access to these features in sensor settings.
Show Upgrade plan tag next to unavailable feature and link to 

English, other languages: cloud.ruuvi.com
Finnish: cloud.ruuvi.com/fi

When main feature, don't dim title
When sub feature, such as Alert delay, dim the feature

![Image](https://github.com/ruuvi/com.ruuvi.station.webui/assets/50437378/6b186397-a481-4870-a7d8-94b61cbfbdfb)

**Comment by laurijamsa** [comment]
Alignment of the Update plan button in here does not seem quite correct. The Upgrade plan text looks also too big (or the button too small).

![Image](https://github.com/ruuvi/com.ruuvi.station.webui/assets/1311912/943cc6fd-d252-4b8a-aff0-4e4550aef297)

Same button comments here:


![Image](https://github.com/ruuvi/com.ruuvi.station.webui/assets/1311912/e4ef8a1e-a97d-4961-9d17-eb8632081c6e)

Free plan sensor shows no alert settings but cloud connection setting is still shown. We need to discuss about this is it really what we want to do. Probably would make sense not to hide any alert settings anymore and add update plan buttons on each of them.


![Image](https://github.com/ruuvi/com.ruuvi.station.webui/assets/1311912/c46279a2-67f8-4ad6-b217-a3f394a6d252)


Finnish "Päivitä Suunnitelma" is not right. "Päivitä tilaus" would be correct. In Swedish "Uppgradera Plan" should be probably without the capital P.

**Comment by markoaamunkajo** [comment]
QA passed
