### ISSUE TITLE
Vunerability report in GitHub (non-critical)

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.webui#397]
Description:

Discussed with Otso, he said that this is non-critical but assign to you @io53 so it's not missed.

![Image](https://github.com/ruuvi/com.ruuvi.station.webui/assets/50437378/f628cfb2-a97e-4734-aecd-6dc1f9bcc4bb)

**Comment by laurijamsa** [comment]
Please close if you think all is done @io53
