### ISSUE TITLE
Show last updated value on the dashboard cards

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/com.ruuvi.station.webui#40]
Let's wait a design file before implementing. Assigning to S-M.

**Comment by sini-maaria** [comment]
Here is the layout:

<img width="800" alt="Screenshot 2021-09-09 at 20 15 34" src="https://user-images.githubusercontent.com/19531763/132732710-86914dd5-24dd-4b7c-9c5d-8e0ccb7bc5bf.png">

**Comment by laurijamsa** [comment]
The font looks too big. Please make it a bit smaller.

![image](https://user-images.githubusercontent.com/1311912/133277354-7734d6c0-b54d-4df7-8389-d7f953195305.png)

**Comment by io53** [comment]
Now it's 12px, down from 16px
