### ISSUE TITLE
Show latest value under alert sliders

### ISSUE THREAD

**Issue by io53** [ruuvi/com.ruuvi.station.webui#401]

**Comment by laurijamsa** [comment]
In my settings I have adjusted 0,1 resolution for hPa:

<img width="190" alt="image" src="https://github.com/ruuvi/com.ruuvi.station.webui/assets/1311912/a94b73b7-1248-4a07-8a47-856eff67ee0c">

<img width="269" alt="image" src="https://github.com/ruuvi/com.ruuvi.station.webui/assets/1311912/691d172d-1380-43cb-a147-5fd506891c25">

But latest measured under the slider shows different precision:

<img width="365" alt="image" src="https://github.com/ruuvi/com.ruuvi.station.webui/assets/1311912/18dcebef-bfbd-42a3-b904-475ab6a5818f">
