### ISSUE TITLE
Support temperature range for external temp sensor

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.webui#411]
Description:

Improve alert range for temperature when using ext temp sensor

Allow adding any value to beyond current min-max limitation
When edited, this value is used, with condition that min is smaller than max because app cannot know that external temperature sensor is used
We will not adjust slider

**Comment by markoaamunkajo** [comment]
@io53 Looks like on mobile side devs (latest dev iOS build) have found a way to dynamically adjust the slider for external sensor.
Would you take a look if it's also possible on web? If not, we will go with this solution.

**Comment by io53** [comment]
@markoaamunkajo Sure, no problem. So if you set max value to 120, the slider should go to 120 until you have saved a smaller value?

**Comment by markoaamunkajo** [comment]
@io53 the min and max supported temperature range should be limited to -55 C - 150 C
Please don't allow saving when value is outside this range.

![Image](https://github.com/ruuvi/com.ruuvi.station.webui/assets/50437378/9f2fca57-d453-464d-8d54-c66f48f035e6)

**Comment by markoaamunkajo** [comment]
Works ok for me

**Comment by markoaamunkajo** [comment]
QA passed
