### ISSUE TITLE
Migrate from CRA to Vite

### ISSUE THREAD

**Issue by io53** [ruuvi/com.ruuvi.station.webui#420]

**Comment by markoaamunkajo** [comment]
@io53 in incognito mode none of the charts are loading for me on Chrome Mac desktop

![Image](https://github.com/user-attachments/assets/b90d2598-6547-4210-96c1-cc99b4839963)
![Image](https://github.com/user-attachments/assets/924e0b90-f114-4802-adda-fca286b2e2fa)

**Comment by markoaamunkajo** [comment]
I also tested same on Safari and I saw

1. The something went wrong page shown briefly without loading the Ruuvi mascot
2. Then dashboard loaded normally including charts

Now also Chrome desktop loaded normally for me including charts

It seems suspicious

**Comment by markoaamunkajo** [comment]
@io53 the issue when loading zoomed chart was reproduced now on Chrome desktop (first time was Opera Mac)
I was playing around with Units and resolutions on Safari and returned back to Chrome later, reloaded page and the issue started appearing for me on chart that making selection area to zoom will freeze the chart for some time before loading view.


https://github.com/user-attachments/assets/9263985c-44fb-46d6-8f78-61cf3b1b4310

**Comment by markoaamunkajo** [comment]
I spent considerable time testing this issue and it seems that chart loading is now fixed or at least unreproducable.
