### ISSUE TITLE
Possible to get blank screen when loading Ruuvi Station with slow internet

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.webui#425]
Description:

User is on EDGE connection and signed in to Ruuvi Station on Mac Chrome incognito window.
For some unknown reason when dashboard finally loads cards it becomes completely blank and it will not finish loading even after 30 minutes waiting.

https://github.com/user-attachments/assets/d05dcf72-54f6-46a0-992d-c43828afe886

**Comment by io53** [comment]
What will be shown in case shit hits the fan:

![Image](https://github.com/user-attachments/assets/39e299ba-8972-4f17-95bd-6aa4b6c20d77)

**Comment by markoaamunkajo** [comment]
Now it seems impossible to get slow internet issue appearing even with 100% loss simulation...
I think this should be tested together with server issues.

**Comment by markoaamunkajo** [comment]
I have seen this design now, works for me, moving to done.
