### ISSUE TITLE
Improve compare page loading and fix date/time selector

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.webui#426]
Description:

(from Lauri's report)

Time selector doesnt work on compare page.

My sensors had only 2 days of data and 1 week was selected and it showed me 2 days. Also, I expected it to update if I changed the date, same was as normally 🤔 or do we have a reason not to update (zoom if data is downloaded already)?

**Comment by io53** [comment]
I think this is fixed now

**Comment by markoaamunkajo** [comment]
QA passed
