### ISSUE TITLE
Compare sensors: fix battery voltage

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.webui#428]
Describe:

These are some pretty big batteries!
Let's fix the formatting same as on sensor page, please check all of them are matching on Compare page

![Image](https://github.com/user-attachments/assets/7bd1356b-4759-438e-87f3-9388b2ffc509)

**Comment by io53** [comment]
Are you sure you didnt just accidentally put 1000 batteries in you tags? 😅

**Comment by markoaamunkajo** [comment]
Mine is the new high voltage version! 😆

**Comment by markoaamunkajo** [comment]
@io53 we want to improve strings in this:

![Image](https://github.com/user-attachments/assets/7c0b0127-f429-414e-9909-adf97fb61643)

To this:

![Image](https://github.com/user-attachments/assets/d0e817d1-d7b3-40a6-8c3d-7eed8e4c3f65)


Looks like in localisation file this is used elsewhere so possibly need to make new ones.
