### ISSUE TITLE
Check image size and format limitations in app

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.webui#429]
Description:

Check image size and format limitations in app

**Comment by markoaamunkajo** [comment]
640heif - blocked
1280 heif - blocked
1920 heif - blocked
heic 1920x1280 - blocked
iOS proraw_max - blocked
iOS max - blocked
iOS proraw_12mp - blocked
jpg 1920x1280
jpg 6720x4480
jpg 8974x6434
jpg 2400x1720
jpg 1920x455
jpg 8192x2932
jpg 8268x1960
gif animation (only still image supported)
png 2400x1720
tiff 2400x1720 - NO (gets stuck in uploading)
webp 1920x1280

**Comment by markoaamunkajo** [comment]
@io53 should we be able to support few more image formats?
Check the comment about TIFF, for me file upload never finished so I expect an error happened.

**Comment by io53** [comment]
Image format depends on the browser in the current implementation. For example in safari both TIFF and HEIC works.
Supporting more would require us to use some image library which seem to be a bit overkill for our use.
I added an error toast if it fails to convert the image to jpg.

**Comment by markoaamunkajo** [comment]
Checked also language file, all good.
