### ISSUE TITLE
Login page content is missing some paddings

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/com.ruuvi.station.webui#43]
Looks too tight to me:

![image](https://user-images.githubusercontent.com/1311912/131842716-291f4427-7ce6-4893-a60b-ad93a8b7303e.png)

Also Fi and Sv links have empty spaces:

![image](https://user-images.githubusercontent.com/1311912/131842870-6fbab41a-3367-4264-8000-062b705aae96.png)
![image](https://user-images.githubusercontent.com/1311912/131842901-a6ef9c8c-05bb-462d-af60-e4b5e6e0c3d1.png)

The En doesn't have that problem:

![image](https://user-images.githubusercontent.com/1311912/131842944-7882fe16-1211-4a6f-9596-de3f29bbfdbd.png)

Make the email input field also auto selected when opening the page. And also the code input field.

**Comment by markoaamunkajo** [comment]
@laurijamsa this looks good to me. Reopen if still looks weird to you.
