### ISSUE TITLE
Mobile landscape viewport fixes

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.webui#430]
Description:

Looks like some alignments are off on mobile viewports.

iPhone 14 Pro landscape:

![Image](https://github.com/user-attachments/assets/5d62df8e-bb0e-4c4c-bda7-38e32a0572d9)
![Image](https://github.com/user-attachments/assets/76513cf9-5f73-4c63-a38f-4ab68af59cd7)

Android Chrome landscape:

![Image](https://github.com/user-attachments/assets/02782ca0-5027-4de8-a0b6-8332dd529c7d)
![Image](https://github.com/user-attachments/assets/899a3389-f3a7-4939-929f-c8f00429a816)

**Comment by io53** [comment]
Tweaked according to specs in telegram. Hopefully I got it right. Note that android landscape will go to desktop view on some phones still, I think its the correct behavior.

**Comment by markoaamunkajo** [comment]
QA passed
