### ISSUE TITLE
RSSI alert manual range should only allow correct values

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.webui#436]
Description:

RSSI alert setting alert threshold range manually should only allow correct values.

i.e. in case user currently reverses values max -30 and min 0 in WebUI this makes the sensor card to generate error for me.

**Comment by io53** [comment]
@markoaamunkajo I also found an issue with temperature & pressure sliders when using unit other than C & Pa so please test that it works correctly.

**Comment by markoaamunkajo** [comment]
Checked all, works for me
