### ISSUE TITLE
1970's date shown on chart

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.webui#445]
Description:

The datapoint inspector is able to show a date in the 1970's first time chart is loaded.
This was replicated on Opera Mac browser, and it shows very very briefly on the inspector, you can barely notice it from the video.

![Image](https://github.com/user-attachments/assets/a138ab52-08f6-47ff-83ed-c2fb57b7490d)
https://github.com/user-attachments/assets/fc2aa4ae-ed2f-4129-a886-16781dfc7b8f

**Comment by markoaamunkajo** [comment]
Let's fix the compare view too

**Comment by io53** [comment]
compare view should not hide the datapoint inspector

**Comment by markoaamunkajo** [comment]
QA passed
