### ISSUE TITLE
Add an option to use a dark theme

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/com.ruuvi.station.webui#45]
Let's specify color codes and then implement.

**Comment by laurijamsa** [comment]
I like how the dark theme toggle switch is working on this site:

https://pancakeswap.finance/swap

**Comment by sini-maaria** [comment]
**Sensor view**
(The colors may change a bit in the future when I have the time to create some logic between light and dark mode. But you can start with these.)

![ruuvi-web-app-dark-sensor](https://user-images.githubusercontent.com/19531763/171374785-56a8532a-b010-4fce-8a5c-409f11bcf17f.jpg)

Color codes from the top to the bottom:

Menu bg: #001d1b, 95%

Subtitle aqua: #00cebb, 80%

Arrows: #fff, opacity 100%
Arrows, circle:
bg: #00413f
border: #fff
opacity: 30%

Boxes:
bg: #00cdb9
icon: #00ae94, 50%
active border: #00cdb9, 100%

Date selection button:
bg: #00413f
border: #fff
opacity: 30%

Graph:
Lines on the background: #fff, 30%
Graph bg: #00cdb9, 30%

Accordion bg: #003434
Accordion open area bg: #003434, 50%
Accordion icons: #fff, 30%

**Comment by sini-maaria** [comment]
Please take a look at the icons on alert settings. Also the arrow on accordion could be lighter/more visible.

**Comment by sini-maaria** [comment]
Changes to the original layout:

- Let's drop the background image on sensor cards on dashboard view. 

- I will look for a suitable generic background image for the dashboard and sensor page.

**Comment by sini-maaria** [comment]
- Remove header background color (white) on light mode dashboard.
- On dark theme, accordion icons (arrow and pen) should be more visible. For example 50% white. 
- Here pen icons have different opacity:
<img width="391" alt="Screenshot 2022-07-11 at 20 06 06" src="https://user-images.githubusercontent.com/19531763/178319230-ae5bd089-c3d1-4057-ad07-8f3a2066bee6.png">
.

**Comment by sini-maaria** [comment]
These are not fixed yet:
- Remove header background color (white) on light mode dashboard. (On the dashboard header, behind the ruuvi logo.)
- Here pen icons have different opacity...

**Comment by sini-maaria** [comment]
Small numbers on the chart (X/Y) should be 100% white.

<img width="1513" alt="Screenshot 2022-07-18 at 19 15 20" src="https://user-images.githubusercontent.com/19531763/179556096-4d5c44d9-a724-4804-954e-e9be0ceb0129.png">
