### ISSUE TITLE
Add support for version filter in banners

### ISSUE THREAD

**Issue by io53** [ruuvi/com.ruuvi.station.webui#454]

**Comment by markoaamunkajo** [comment]
Banner is shown according to matching release version number

{
    "plan": "",
    "key": "20241021",
    "version": "1.2.1",
    "en": "...",
    "fi": "...",
    "sv": "..."
}

**Comment by markoaamunkajo** [comment]
@io53 
I tested with new key date and new version that is different from version info at footer of page.
I was expecting banner to get hidden on dev, but it didn't disappear anywhere. I tested on Chrome in incognito mode, sign in and sign out in between tests.

**Comment by markoaamunkajo** [comment]
Cache fooled me. Retested and it works.
