### ISSUE TITLE
"X ago" should be updated continuously

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/com.ruuvi.station.webui#46]
On page load, the "0m ago" is updated and all is good. But when time goes on and user doesn't refresh the page, the counter doesn't count and it still says "0m ago" even if the data shown is actually older.

We have decided not to automatically refresh the page for now, but the updated time should be updated. And actually it should show "35 s ago", "36 s ago", "37 s ago" and after 1 minute has passed, it should be "1 min 1 s ago". Just like the mobile apps do.

We can add auto cloud refresh later if decided so, but let's fix this one first. We'll need this same thing on the web dashboard once its layout outlook has been designed first.

**Comment by markoaamunkajo** [comment]
QA passed, no auto refresh yet
