### ISSUE TITLE
On dashboard, some sensors show dates and some don't

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/com.ruuvi.station.webui#50]
![image](https://user-images.githubusercontent.com/1311912/132351754-0fde3cd8-e0b2-47fb-98c7-10d34c7a3364.png)

Let's unify this so that dates would be shown on every sensor. It wont be an optimal solution and more tuning will be needed later. But for now, let's unify these.

This is related to the user feedback here:

https://f.ruuvi.com/t/measurement-graph-web-page/4948

**Comment by markoaamunkajo** [comment]
QA passed
