### ISSUE TITLE
Humidity calibration mismatch

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.webui#52]
Description:

Humidity calibration % is not matching with Android app and Webapp
Units used in Android app: Fahrenheit, Relative %, Pascal

![humidity_calibration](https://user-images.githubusercontent.com/50437378/132613238-c43f6187-9c21-4414-aad9-4d42112f734c.jpg)

**Comment by io53** [comment]
@markoaamunkajo I cannot reproduce this. It just shows the number that is returned from the backend, no funny business. Can you confirm that the page did not just need to be refreshed?

**Comment by markoaamunkajo** [comment]
@io53 looks like this changes to 16.37% every time if I change android app to show Fahrenheit instead of Celsius units. It changes only on web not on Android device.

**Comment by io53** [comment]
You are correct, jikes how did that slip happen. Nice find

**Comment by laurijamsa** [comment]
I didn't test this really well but as Marko is sleeping and we'd like to push the other pending tasks to production, I've added a ready to deploy tag here. Marko can test it again in production.

**Comment by markoaamunkajo** [comment]
QA Passed
