### ISSUE TITLE
Fix FI date format

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.webui#56]
Description:

User suggested fixing date format in Finnish language dd/mm -> dd.mm.

**Comment by laurijamsa** [comment]
A dot is missing and an extra zero is shown:

![image](https://user-images.githubusercontent.com/1311912/133275272-d1b0b54e-f173-4dd0-93d7-034264efe0d0.png)

Shoud be "12.9." and not 12.09"

**Comment by DG12** [comment]
Or **12.1**  ?
