### ISSUE TITLE
After >1h without data update, updated counter breaks

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/com.ruuvi.station.webui#57]
![Screenshot_20210913-215847_Messenger](https://user-images.githubusercontent.com/1311912/133141297-d31643d8-245a-406e-bf28-4b93ca2e7917.jpg)

After 1h, it shows hours AND all minutes.

**Comment by laurijamsa** [comment]
I don't have a chance to test this properly but let's push it to production if you're pretty sure that it's fixed.

**Comment by markoaamunkajo** [comment]
QA passed
