### ISSUE TITLE
Enable zooming with 2 fingers on mobile devices

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/com.ruuvi.station.webui#58]

**Comment by laurijamsa** [comment]
I see some ux issues:

- When scrolling the page with one finger and gripping on the graph, the graph should not start to move
- Horisontal and vertical zoomings aren't working, two fingers affect the both at the same time
- 1 min auto refresh resets the zooming level
- When zooming out (1 day selected), the graph doesn't download more data even if it's available -> maybe could be fixed by disabling zooming out when selected timeframe is already fully shown

Let's discuss which ones we can fix easily and which will require more effort.

**Comment by io53** [comment]
Disable one finger scroll on graph
