### ISSUE TITLE
Alerts UI

### ISSUE THREAD

**Issue by sini-maaria** [ruuvi/com.ruuvi.station.webui#65]
Please compare the design file and current layout for alerts and make them to look the same:
- Font sizes, colors and weights
- Colors on on/off options #d4ede8
- Remove the blue highlight lines on top and bottom of title rows
- Elements' places (min/max numbers)
- Paddings 
- Remove extra divider lines and use sliders as dividers. -> All the alert options are visible at once, they are not clickable / sub items on the accordion menu.

Don't use grey anywhere on the whole Web UI. Our blue (greyish) color, mainly used as border color is: #d4ede8

<img width="1044" alt="Screenshot 2021-10-14 at 12 41 44" src="https://user-images.githubusercontent.com/19531763/137292903-66b69e9b-ebaa-4b75-bd7e-6e438ba579a4.png">

<img width="1135" alt="Screenshot 2021-10-14 at 12 46 18" src="https://user-images.githubusercontent.com/19531763/137293637-14a0372c-7bdd-4c2b-8a20-7910ba5aeb74.png">

**Comment by io53** [comment]
remove slider air pressure decimals

**Comment by io53** [comment]
remove dialog close button blue focus
