### ISSUE TITLE
User without account or sensors should show error / warning - improvement

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.webui#66]
Unknown user should show some kind of error like "no sensors for user :xxxxx"
<img width="1276" alt="devstationNoData" src="https://user-images.githubusercontent.com/2365961/137985060-7e7c26e2-988b-48ee-8e29-06b044ee2ea1.png">

**Comment by DG12** [comment]
Oops. :-) Good catch, don't know how I managed to do that .
It would be nice if some message was presented like "no account" or "no sensors for xxxxx"

**Comment by laurijamsa** [comment]
omistajuus -> omistajuus. (add a period)

![image](https://user-images.githubusercontent.com/1311912/145347188-d960ea53-7fa8-4cc7-afa4-44383923e558.png)

S to s:
![image](https://user-images.githubusercontent.com/1311912/145347111-08184b58-8fe6-40aa-aa7f-5d120bfb32f0.png)

Remove w:
![image](https://user-images.githubusercontent.com/1311912/145346998-20d1c88f-5e61-4223-8175-b411b35ef57c.png)
