### ISSUE TITLE
Zoom out / reset zoom button

### ISSUE THREAD

**Issue by ojousima** [ruuvi/com.ruuvi.station.webui#67]
Right now after zooming in the only way to reset zoom level is to reselect a time range

**Comment by laurijamsa** [comment]
@sini-maaria let's plan how the zooming feature would be easier to notice and use. First of all there could be a magnifying glass icon somewhere that could give a tip about how to zoom. And if user has zoomed in, the icon could change to something else ("return to 1:1" icon) that would reset the zooming level.

**Comment by sini-maaria** [comment]
Let's add "Zoom" link with info icon. When user clicks this link, it opens a popup with info text how to use zoom.

![Screenshot 2021-12-20 at 11 52 13](https://user-images.githubusercontent.com/19531763/146747922-d011889f-d9d6-41bc-ac6d-f38eeb4c129b.png)

Icon file in Telegram.
