### ISSUE TITLE
Setting temperature alerts via input values are in Centigrade although user prefers Fahrenheit -Defect

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.webui#68]
Set temp limits to 70..78 display shows no limits are 158..172 !

Additionally limit should be restricted to values consistent with physical device limits i.e. -40 .. +85 °C

Also display is not in users locale, in this case degrees F with comma delimiting hundredths should be dot.

I really like being able to set limits via value i.e. not slider

**Comment by io53** [comment]
User format limit inputs now works for temperature and pressure
