### ISSUE TITLE
X-axis after zoom should be adjusted

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.webui#69]
After zooming to view a detailed section of the temperature, all x-axis values show 24.10

Original view 2 days, selected section 5hour
<img width="1192" alt="RuuviWebx-axistrouble" src="https://user-images.githubusercontent.com/2365961/138922372-5c4570d3-84eb-47ed-8459-48d4c3119d63.png">
s

**Comment by laurijamsa** [comment]
Dashboard has 72 hours and it shows dates like it should but I'm wondering how it shows 4 different dates? Something is off and this need some investigation.
Old:
![image](https://user-images.githubusercontent.com/1311912/142366945-5af2dad9-4349-4311-8a89-7596c6f8580e.png)

New: 
![image](https://user-images.githubusercontent.com/1311912/142366885-1e5fe0f3-4025-4d6b-8e4e-1339232e6ba4.png)

**Comment by io53** [comment]
Todo: Use hours if x-range is <= 72h. Replace 00:00 with date
