### ISSUE TITLE
Cache sensor data

### ISSUE THREAD

**Issue by io53** [ruuvi/com.ruuvi.station.webui#71]
Store sensor data locally and only fetch newer data.
Investigate how much data is reasonable to keep locally

**Comment by laurijamsa** [comment]
Reloading test (command + R)

Old:
![image](https://user-images.githubusercontent.com/1311912/140975810-abdc6070-49fe-48de-8792-f93908bf8b0a.png)

New:
![image](https://user-images.githubusercontent.com/1311912/140975874-ec90dc15-0c8d-4e5b-a32a-171120ca2152.png)

Auto refresh test (wait 1 minute):

Old:
![image](https://user-images.githubusercontent.com/1311912/140976051-4b6de514-1b36-426b-954a-98e75f4d9f18.png)

New:
![image](https://user-images.githubusercontent.com/1311912/140976280-20886a6c-7b2e-40c6-834a-51c4217d7e8e.png)

If these are expected results, then, let's deploy :)

**Comment by io53** [comment]
Yep, that's what we want!
