### ISSUE TITLE
RuuviTag PRO shows air pressure even there's no air pressure sensor

### ISSUE THREAD

**Issue by hakunti** [ruuvi/com.ruuvi.station.webui#73]
Customer reported that RuuviTag Pro doesn't show air pressure on app but it's showing on web user interface.

**Comment by hakunti** [comment]
![image](https://user-images.githubusercontent.com/25771106/139585666-50324bda-97fc-44dc-a1ed-9fd0bb080f39.png)

**Comment by hakunti** [comment]
Air pressure is always flat, device RuuviTag Pro 3in1. No pressure sensor on board.

**Comment by ojousima** [comment]
RuuviTag sends "0xFFFF" as air pressure value when air pressure is not available. It should be interpreted as not available

**Comment by ojousima** [comment]
This also affects humidity, and probably all other values too
