### ISSUE TITLE
Temperature legend correctly labeled F but values AND GRAPH are C

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.webui#76]
See attached

<img width="371" alt="DevstationYaxisWrongScale" src="https://user-images.githubusercontent.com/2365961/142350012-1fbea817-844b-4900-8f18-ab40d033051b.png">

webui. displays correctly:
<img width="386" alt="WebuiYaxisGoodScale" src="https://user-images.githubusercontent.com/2365961/142350208-7b8372f7-fcd0-48b1-a1f5-b3a2985fa47f.png">

**Comment by io53** [comment]
@DG12 Can you confirm that this is still an issue? I cannot seem to reproduce it

**Comment by DG12** [comment]
Please refer to multiSensor Window with settings F, title is F , graph is C issue#82

**Comment by DG12** [comment]
<img width="637" alt="singleSensorClaimsF_ActualC" src="https://user-images.githubusercontent.com/2365961/145042472-a849e1e7-1669-4c6f-88ec-48d4da3b2627.png">
