### ISSUE TITLE
One time code is expired when creating a new account

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/com.ruuvi.station.webui#83]
1) Open a new Chrome incognito window
2) Open station.ruuvi.com
3) Enter an email that hasn't been used before
4) Enter the code
5) Result:

![image](https://user-images.githubusercontent.com/1311912/145227160-5e8dbd78-abfe-4d32-a286-7ce7efdc22a2.png)

After trying again with the same email, the second code works ok.

I couldn't replicate this with the Android app, so that's why this issue lives in the webui repo and not in the backend repo.

**Comment by io53** [comment]
Did we reach any conclusion with this? I've not managed to reproduce it

**Comment by laurijamsa** [comment]
We haven't been able to reproduce this. Closing.

**Comment by hakunti** [comment]
https://f.ruuvi.com/t/kirjautuminen-station-ruuvi-com-vaatii-aina-kaksi-kirjautumista/5260/3

**Comment by laurijamsa** [comment]
Haven't heard such problems anymore and on the forum, OP assumed Chrome updates were the fault. Closing.

**Comment by ojousima** [comment]
I think these reports stopped after we implemented old code cleanup in Cloud side
