### ISSUE TITLE
Make ESC key to close "a window"

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/com.ruuvi.station.webui#85]
Personally I use ESC a lot when escaping from windows I want to close. I think would be handy to be able to close windows on the web app by hitting the ESC.

By a "window", I mean sensor and settings views that have the "X" buttons:

![image](https://user-images.githubusercontent.com/1311912/145371318-25a774f1-fcaf-42da-9da4-467b25ff8d45.png)
![image](https://user-images.githubusercontent.com/1311912/145371355-5912cb9b-2383-48ee-a254-9f11b4319a77.png)

**Comment by io53** [comment]
Escape = close button
ArrowLeft = left arrow button
ArrowRight = right arrow button

**Comment by laurijamsa** [comment]
Arrows work ok. ESC is currently returning user always to the dashboard even if user opened settings page on top of a sensor page. Would be better that the settings view would behave similarly with the custom alert description popups for example. ESC closes them just nicely.

**Comment by io53** [comment]
I added some logic to go back to the correct place, but back from settings can feel a bit clumsy as it's a separate route. If it's too clunky we can change the route into a popup in another task
