### ISSUE TITLE
Enhance the history length selector tool (add calendar etc.) 

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/com.ruuvi.station.webui#88]
In this issue we can discuss about how the selection tool should look like. This would replace the current implementation we have.

I personally like the one Toggl is having:

Configuration view:

![image](https://user-images.githubusercontent.com/1311912/145376922-43be317a-7fe5-4ab6-903d-53d24900d976.png)

Selected:

![image](https://user-images.githubusercontent.com/1311912/145377034-6321c774-5075-48b7-8872-8d472a47ac44.png)

![image](https://user-images.githubusercontent.com/1311912/145377074-e255603f-a4b4-49a0-b65d-a57ac9ed24b9.png)

![image](https://user-images.githubusercontent.com/1311912/145377104-7b046f36-15d6-4a5c-a7b6-fc04515d45bf.png)

**Comment by io53** [comment]
https://github.com/gpbl/react-day-picker
This datepicker lib looks promising

**Comment by markoaamunkajo** [comment]
Description:

This library looks good, let's use it.


1. Add a "Custom..." option to range selector, first option in the list
2. Show calendar type "Selecting a Range of days"
3. Show selected range of days in history view

Let's make a demo first and then add styling.

**Comment by io53** [comment]
https://devstation.ruuvi.com/daypicker/
