### ISSUE TITLE
selecting a single sensor reports load data error type error - devastation  v0.2.4

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.webui#91]
<img width="621" alt="LoadDataerror" src="https://user-images.githubusercontent.com/2365961/146290744-1a9af582-03d2-4f71-8cc7-9c8ea671c173.png">

Is there?, should there be? , a separate repository for issues to devastation ?

**Comment by io53** [comment]
Nope, this is the one.
I fixed the issue, I hope. Can you check if it's gone? :)

**Comment by DG12** [comment]
Looks good. Thanks
