### ISSUE TITLE
Simplify alert settings and unify with mobile

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/com.ruuvi.station.webui#93]
Make the titles look same as on mobile (Temperature -> Temperature (°F))

Simplify the values not to show ",00" when there is no need to do it (to make it look more clean). However, keep the possibility to adjust manually with a better precision.

Currently:

![image](https://user-images.githubusercontent.com/1311912/146334810-c1662f99-6eb9-45ba-8625-a5b4e7b13edc.png)

Same settings on mobile:

![image](https://user-images.githubusercontent.com/1311912/146334875-f3a9bd9e-c4cf-4a32-8ee8-0ea47d7cc195.png)

Another thing to enhance is to increment values always with full digits when adjusting alert settings sliders (1 degree in this case on the video):

https://user-images.githubusercontent.com/1311912/146336126-d69c4e05-343f-4150-88ad-afb1fb187ed5.mov

**Comment by markoaamunkajo** [comment]
![Screenshot 2022-01-16 at 18 05 22](https://user-images.githubusercontent.com/50437378/149657348-d66bc400-21ea-48d9-a161-41e815e37e01.png)

@io53 it's possible to save impossible values as range when editing manually.

**Comment by io53** [comment]
True, good catch.

**Comment by laurijamsa** [comment]
Note that we support only relative humidity alerts but currently also absolute or dew point definitions are shown on the alert section. Force (%) to be shown always.

![image](https://user-images.githubusercontent.com/1311912/150752778-33f7343a-2732-4a6f-952b-f6c47aa77693.png)
![image](https://user-images.githubusercontent.com/1311912/150752834-339bc2cd-3d77-42b2-afea-08e02382b0b2.png)
